-- Gemini-extracted: San Jose, CA
-- Generated: 2026-04-07T23:01:39.052Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('California', 'california', 'CA') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'california'), 'Santa Clara County', 'santa-clara-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'santa-clara-county' AND state_id = (SELECT id FROM states WHERE slug = 'california')), 'San Jose', 'san-jose', 37.3382, -121.8863, 1013240) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory Dwelling Units (ADUs)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home occupations', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community facilities (with special permits)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family manufactured homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplexes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Condominiums', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Triplexes and multiple-family structures (apartments)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouses, townhomes and condominium clusters', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day care centers', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Golf courses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks, public and private', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public and quasi-public uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public utility facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-unit residential developments', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Higher density residential-commercial mixed-use development', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('General Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Alcohol, off-sale - beer and/or wine', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Classroom use only (no driving courses or onsite vehicle storage)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail art studios', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesaling', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service establishments serving employees of businesses in industrial areas', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouse retail (compatible with adjacent industrial uses)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public eating establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Incidental retail sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Incidental office use', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Extractive industries', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Primary processing industries', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Very limited scale retail sales and service establishments serving nearby businesses and employees (incidental to industrial use)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mid-rise office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light industrial uses (compatible, e.g., food and beverage manufacturing)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Affordable deed-restricted housing (100% affordable)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medium-density residential development', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use development', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private community gathering facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('High-density residential development', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed residential and commercial development', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'R-1', 'r-1', 'Single-Family Residential', 'Intended for single-family homes, setting rules on lot sizes, building heights, and distances between structures to preserve low-density, quiet neighborhoods.', NULL, NULL, 6000, NULL, 20, 20, 5, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Single-family homes', 'Accessory Dwelling Units (ADUs)', 'Home occupations', 'Community facilities (with special permits)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'R-2', 'r-2', 'Two-Unit Residential', 'Promotes and encourages a suitable environment for family life at a slightly higher density than R-1, providing opportunities for duplex and attached dwellings.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Single-family detached dwellings', 'Single-family manufactured homes', 'Duplexes', 'Condominiums', 'Triplexes and multiple-family structures (apartments)', 'Townhouses, townhomes and condominium clusters', 'Churches', 'Day care centers', 'Golf courses', 'Parks, public and private', 'Public and quasi-public uses', 'Public utility facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'R-M', 'r-m', 'Multiple Residence District', 'Intended for multi-unit residential developments containing attached or detached dwelling units, allowing for higher density residential development and higher density residential-commercial mixed-use development.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-m' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Multi-unit residential developments', 'Higher density residential-commercial mixed-use development', 'Accessory Dwelling Units (ADUs)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'CN', 'cn', 'Commercial Neighborhood District', 'Intended to provide for neighborhood-serving commercial uses without an emphasis on pedestrian orientation, supporting neighborhood centers, multi-tenant commercial development, and small corner commercial establishments.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cn' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('General Retail', 'Alcohol, off-sale - beer and/or wine', 'Classroom use only (no driving courses or onsite vehicle storage)', 'Retail art studios', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'CG', 'cg', 'Commercial General District', 'Intended to serve the needs of the general population, allowing for a full range of retail and commercial uses with a local or regional market, including larger commercial centers and regional malls.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cg' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('General Retail', 'Alcohol, off-sale - beer and/or wine', 'Classroom use only (no driving courses or onsite vehicle storage)', 'Retail art studios', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'LI', 'li', 'Light Industrial', 'Intended for a wide variety of industrial uses such as warehousing, wholesaling, and light manufacturing, excluding uses with unmitigated hazardous or nuisance effects.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'li' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Warehousing', 'Wholesaling', 'Light manufacturing', 'Service establishments serving employees of businesses in industrial areas', 'Warehouse retail (compatible with adjacent industrial uses)', 'Public eating establishments', 'Incidental retail sales', 'Incidental office use', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'HI', 'hi', 'Heavy Industrial', 'Intended for industrial uses with nuisance or hazardous characteristics that are best segregated from other uses, such as extractive and primary processing industries.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'hi' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Extractive industries', 'Primary processing industries', 'Very limited scale retail sales and service establishments serving nearby businesses and employees (incidental to industrial use)', 'Warehouse retail (compatible with adjacent industrial uses)', 'Public eating establishments', 'Incidental retail sales', 'Incidental office use', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'MUC', 'muc', 'Mixed Use Commercial District', 'Supports a mix of commercial and residential uses, including neighborhood retail and mid-rise office, with some compatible light industrial uses.', 85, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'muc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Commercial uses', 'Residential uses', 'Neighborhood retail', 'Mid-rise office', 'Light industrial uses (compatible, e.g., food and beverage manufacturing)', 'Retail art studios', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)', 'Affordable deed-restricted housing (100% affordable)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'UR', 'ur', 'Urban Residential District', 'Supports medium-density residential development, mixed-use development, or a broad range of stand-alone commercial uses.', 85, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ur' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('Medium-density residential development', 'Mixed-use development', 'Retail', 'Offices', 'Private community gathering facilities', 'Retail art studios', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-jose'), 'TR', 'tr', 'Transit Residential District', 'Supports new high-density residential or mixed residential and commercial development, located in close proximity to public transit.', 85, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Chapter 20.90 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'tr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-jose') AND pu.name IN ('High-density residential development', 'Mixed residential and commercial development', 'Office', 'Retail', 'Hotels', 'Private community gathering facilities', 'Retail art studios', 'Taproom or tasting room with off-sale of alcohol (in conjunction with winery, brewery, or distillery)') ON CONFLICT DO NOTHING;
