-- Gemini-extracted: San Diego, CA
-- Generated: 2026-04-07T23:00:22.142Z
-- Zones: 2
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('California', 'california', 'CA') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'california'), 'San Diego County', 'san-diego-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'san-diego-county' AND state_id = (SELECT id FROM states WHERE slug = 'california')), 'San Diego', 'san-diego', 32.7157, -117.1611, 1386932) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single Dwelling Units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory Uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple Dwelling Units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Limited Commercial Uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-diego'), 'RS-1-1', 'rs-1-1', 'Residential--Single Unit 1-1', 'The purpose of the RS zones is to provide appropriate regulations for the development of single dwelling units that accommodate a variety of lot sizes and residential dwelling types and which promote neighborhood quality, character, and livability. It is intended that these zones provide for flexibility in development regulations that allow reasonable use of property while minimizing adverse impacts to adjacent properties.', '24/30', NULL, 40000, NULL, 25, 25, '0.08 * lot width', 'Refer to Chapter 14, Article 2 (Parking Regulations)') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-1-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-diego') AND pu.name IN ('Single Dwelling Units', 'Accessory Uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-diego'), 'RM-1-1', 'rm-1-1', 'Residential--Multiple Unit 1-1', 'The purpose of the RM zones is to provide for multiple dwelling unit development at varying densities. The RM zones individually accommodate developments with similar densities and characteristics, establishing development criteria that consolidate common development regulations, accommodate specific dwelling types, and respond to locational issues regarding adjacent land uses.', 30, 0.75, 6000, NULL, 15, 15, 5, 'Refer to Chapter 14, Article 2 (Parking Regulations)') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-1-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-diego') AND pu.name IN ('Multiple Dwelling Units', 'Limited Commercial Uses') ON CONFLICT DO NOTHING;
