-- Gemini-extracted: Sacramento, CA
-- Generated: 2026-04-07T23:03:51.767Z
-- Zones: 7
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('California', 'california', 'CA') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'california'), 'Sacramento County', 'sacramento-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'sacramento-county' AND state_id = (SELECT id FROM states WHERE slug = 'california')), 'Sacramento', 'sacramento', 38.5816, -121.4944, 524943) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Dwelling, single-unit', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling, duplex (limited to corner lots)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Model home temporary sales office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community market (if primary use is not single-unit or duplex dwelling)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Solar energy system, commercial (city property)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Aquaculture, private garden, and urban beekeeping', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling, duplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling, multi-unit', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Temporary residential shelter', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling unit, junior accessory', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling, junior accessory', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Assembly – cultural, religious, social', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Personal services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesale trade', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research and development', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Marijuana testing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community clinic', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Low barrier navigation center', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential hotel', 'Residential') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'R-1', 'r-1', 'Single-Unit Dwelling Zone', 'This zone is intended to provide areas for single-unit dwellings and to protect the characteristics of existing single-unit neighborhoods. It also allows for public and quasi-public uses, and similar and compatible uses appropriate in a medium-density residential environment.', 35, NULL, 5200, NULL, 20, 15, 5, 'See Chapter 17.608 for parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Dwelling, single-unit', 'Dwelling, duplex (limited to corner lots)', 'Model home temporary sales office', 'Community market (if primary use is not single-unit or duplex dwelling)', 'Solar energy system, commercial (city property)', 'Aquaculture, private garden, and urban beekeeping') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'R-2', 'r-2', 'Duplex Dwelling Zone', 'This zone is intended to provide areas for a variety of housing types at densities in the range of 6.1 to 12.0 units per acre. It also provides for public and quasi-public uses, and similar and compatible uses appropriate in a medium-density residential environment.', NULL, NULL, NULL, NULL, 15, 15, 5, 'See Chapter 17.608 for parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Dwelling, duplex', 'Dwelling, multi-unit', 'Temporary residential shelter', 'Dwelling unit, junior accessory') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'R-3', 'r-3', 'Multi-Unit Dwelling Zone', 'The R-3 Zone is intended to provide areas for a wide variety of high-density residential development, including single-unit attached, townhouses, condominiums, and apartment buildings. It also accommodates public and quasi-public uses, and similar compatible uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'See Chapter 17.608 for parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Dwelling, multi-unit', 'Dwelling, junior accessory', 'Assembly – cultural, religious, social') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'C-2', 'c-2', 'General Commercial Zone', 'This zone is intended to provide for a wide range of retail, service, and office uses that serve a community-wide or regional market. It allows for a mix of commercial and institutional uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'See Chapter 17.608 for parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Retail sales', 'Personal services', 'Offices', 'Restaurants', 'Dwelling unit, junior accessory') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'M-1', 'm-1', 'Light Industrial Zone', 'This zone is intended to accommodate light manufacturing, processing, assembly, research, wholesale, and storage uses. It also provides for public and quasi-public uses, and similar and compatible uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'See Chapter 17.608 for parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Light manufacturing', 'Warehousing', 'Wholesale trade', 'Research and development', 'Marijuana testing', 'Community clinic') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'RMX', 'rmx', 'Residential Mixed Use Zone', 'This zone is intended to provide for mixed-use developments that include a mix of residential and office/commercial or single-use residential, office, or commercial, with an emphasis on non-residential uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Off-street parking is not required for nonresidential uses in mixed-use buildings where at least 50% of the building''s square footage is residential.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rmx' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Dwelling, multi-unit', 'Retail sales', 'Offices', 'Low barrier navigation center', 'Residential hotel', 'Community clinic') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'sacramento'), 'OB', 'ob', 'Office Business Low-Rise Mixed-Use Zone', 'This zone is intended to provide for office and business uses, often in a low-rise mixed-use context. It supports a mix of commercial and residential activities.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'See Chapter 17.608 for parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ob' AND z.city_id = (SELECT id FROM cities WHERE slug = 'sacramento') AND pu.name IN ('Offices', 'Retail sales', 'Dwelling, multi-unit', 'Community clinic') ON CONFLICT DO NOTHING;
