-- Gemini-extracted: San Francisco, CA
-- Generated: 2026-04-07T23:02:41.398Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('California', 'california', 'CA') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'california'), 'San Francisco County', 'san-francisco-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'san-francisco-county' AND state_id = (SELECT id FROM states WHERE slug = 'california')), 'San Francisco', 'san-francisco', 37.7749, -122.4194, 873965) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential care facility (6 or fewer persons)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Child care facility (12 or fewer children)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Open space for horticulture or passive recreation', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public structure or use of non-industrial character', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Sale or lease sign', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Three-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Agricultural Uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Agriculture, Neighborhood', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sales and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses (often upper stories)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesale', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Repair activities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail (limited size)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office (limited size)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Maritime activity', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wastewater treatment plants', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'RH-1(D)', 'rh-1-d', 'Residential, House, One-Family (Detached Dwellings)', 'Primarily for single-family detached homes, allowing one dwelling unit per lot. This district typically requires side yards between buildings.', 35, 1.8, 4000, NULL, 'Based upon average of adjacent buildings; up to 15 ft. or 15% of lot depth', 15, 'Requirement based on lot width', NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rh-1-d' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Single-family dwelling', 'Residential care facility (6 or fewer persons)', 'Child care facility (12 or fewer children)', 'Open space for horticulture or passive recreation', 'Public structure or use of non-industrial character', 'Sale or lease sign') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'RH-2', 'rh-2', 'Residential, House, Two-Family', 'Allows for two dwelling units per lot, with the possibility of one unit per 1500 sq. ft. of lot area with conditional use approval.', 40, 1.8, 2500, NULL, 'Based upon average of adjacent buildings; up to 15 ft. or 15% of lot depth', '45% of lot depth, except reductions based on average of adjacent buildings; if averaged, last 10 ft. is limited to 30 ft. and a minimum of 25% of lot depth, but no less than 15 feet', NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rh-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Two-family dwelling', 'Residential care facility (6 or fewer persons)', 'Child care facility (12 or fewer children)', 'Open space for horticulture or passive recreation', 'Public structure or use of non-industrial character', 'Sale or lease sign') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'RH-3', 'rh-3', 'Residential, House, Three-Family', 'Allows for three dwelling units per lot, or up to one unit per 1,000 sq. ft. of lot area with conditional use approval.', 40, 1.8, 2500, NULL, 'Based upon average of adjacent buildings; up to 15 ft. or 15% of lot depth, but no greater than 10 feet if based on adjacent properties', '30% of lot depth, but in no case less than 15 feet', NULL, 'Maximum permitted per § 151') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rh-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Three-family dwelling', 'Residential care facility (6 or fewer persons)', 'Child care facility (12 or fewer children)', 'Open space for horticulture or passive recreation', 'Public structure or use of non-industrial character', 'Sale or lease sign', 'Agricultural Uses', 'Agriculture, Neighborhood', 'Community Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'RM-1', 'rm-1', 'Residential, Mixed (Apartments and Houses), Low Density', 'Allows for three dwelling units per lot or one dwelling unit per 800 sq. ft. of lot area.', 40, 1.8, 2500, NULL, 'Based upon average of adjacent buildings; up to 15 ft. or 15% of lot depth', '45% of lot depth, except reductions based on average of adjacent buildings; if averaged, last 10 ft. is limited to 30 ft. and a minimum of 25% of lot depth, but no less than 15 feet', NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Multi-family dwellings', 'Residential care facility (6 or fewer persons)', 'Child care facility (12 or fewer children)', 'Open space for horticulture or passive recreation', 'Public structure or use of non-industrial character', 'Sale or lease sign') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'RM-2', 'rm-2', 'Residential, Mixed (Apartments and Houses), Moderate Density', 'Allows for three dwelling units per lot or one dwelling unit per 600 sq. ft. of lot area.', 40, 1.8, 2500, NULL, 'Based upon average of adjacent buildings; up to 15 ft. or 15% of lot depth', '45% of lot depth, except reductions based on average of adjacent buildings; if averaged, last 10 ft. is limited to 30 ft. and a minimum of 25% of lot depth, but no less than 15 feet', NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Multi-family dwellings', 'Residential care facility (6 or fewer persons)', 'Child care facility (12 or fewer children)', 'Open space for horticulture or passive recreation', 'Public structure or use of non-industrial character', 'Sale or lease sign') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'NC-1', 'nc-1', 'Neighborhood Commercial, Cluster', 'Intended for small-scale commercial clusters serving immediate neighborhood needs, often with one commercial story.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Retail sales and services', 'Offices', 'Residential uses (often upper stories)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'NC-2', 'nc-2', 'Neighborhood Commercial, Small Scale', 'Designed for small-scale neighborhood commercial areas, typically allowing up to two commercial stories.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Retail sales and services', 'Offices', 'Residential uses (often upper stories)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'NC-3', 'nc-3', 'Neighborhood Commercial, Moderate Scale', 'Intended for moderate-scale neighborhood commercial areas, typically allowing three or more commercial stories.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Retail sales and services', 'Offices', 'Residential uses (often upper stories)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'M-1', 'm-1', 'Light Industrial', 'Permits light manufacturing, wholesale, and repair activities, with some restrictions on heavy industry and housing. Retail and office uses are limited in size.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Light manufacturing', 'Wholesale', 'Repair activities', 'Retail (limited size)', 'Office (limited size)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-francisco'), 'M-2', 'm-2', 'Heavy Industrial', 'Intended for industrial activities that are not compatible with other uses, such as wastewater treatment plants and maritime activity.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-francisco') AND pu.name IN ('Heavy industrial uses', 'Maritime activity', 'Wastewater treatment plants') ON CONFLICT DO NOTHING;
