-- Gemini-extracted: St. Petersburg, FL
-- Generated: 2026-04-07T23:09:42.207Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Florida', 'florida', 'FL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'florida'), 'Pinellas County', 'pinellas-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'pinellas-county' AND state_id = (SELECT id FROM states WHERE slug = 'florida')), 'St. Petersburg', 'st-petersburg', 27.7676, -82.6403, 258308) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory dwelling units (e.g., garage apartments)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family houses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Triplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Fourplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Rental apartments', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Condominiums', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood-serving retail and service uses (adjacent to this zoning category)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory dwelling units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory uses and structures', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhomes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment buildings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use buildings', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices (conversion from single-family homes)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Limited retail uses (conversion from single-family homes)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Workforce housing', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed uses with multifamily structures', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Workforce housing (with additional density)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory uses and structures (not limited to 67% of principal use)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple-family residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small-scale office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'NT-1', 'nt-1', 'Neighborhood Traditional Single-Family-1', 'Primarily for single-family homes, allowing accessory dwelling units. Design guidelines ensure compatibility with existing neighborhood character and limit driveway locations to the rear alley.', NULL, 'Residential FAR limits apply, consistent with established neighborhood patterns.', NULL, 'Generally 60-65% (for ADUs, likely applies generally).', 'Reduced setbacks, front porches and primary entrances facing the avenue.', 'Driveways, garages, and utility uses limited to the rear of the property.', NULL, 'Vehicular access from the rear alley. Accessory dwelling units require parking (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nt-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Single-family homes', 'Accessory dwelling units (e.g., garage apartments)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'NTM-1', 'ntm-1', 'Neighborhood Traditional Mixed-Residential', 'Intended for renovations and redevelopment in traditional neighborhoods, respecting existing patterns. Allows a variety of urban housing choices in low to medium density building types, with a maximum of 4 units per building. Supports walkability, attainable housing, and transitions from mixed-use corridors.', 24, NULL, NULL, NULL, NULL, 'Driveways, garages, and utility uses limited to the rear of the property.', NULL, 'Parking would go in the public, passable alley. Accessory dwelling units require parking (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ntm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Single-family houses', 'Accessory dwelling units (e.g., garage apartments)', 'Duplex', 'Triplex', 'Fourplex', 'Rental apartments', 'Townhouses', 'Condominiums', 'Neighborhood-serving retail and service uses (adjacent to this zoning category)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'NS-1', 'ns-1', 'Neighborhood Suburban Single-Family-1', 'Reserved for single-family residential neighborhoods of the suburban style. Single-family homes are the principal use. Driveways and garages are allowed in the front yard according to specific design criteria.', 36, 'Not applicable for residential uses. Maximum nonresidential intensity (floor area ratio) is 0.35.', 5800, 60, 20, NULL, 3, 'Driveways and garages are allowed in the front yard (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ns-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Single-family homes', 'Accessory dwelling units') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'NSM-1', 'nsm-1', 'Neighborhood Suburban Multi-Family-1', 'Intended for multi-family residential development in suburban neighborhoods.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to the Use Permissions and Parking Requirements Matrix (Section 16.10.020.1).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nsm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Multi-family dwellings', 'Accessory uses and structures') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'CRT-1', 'crt-1', 'Corridor Residential Traditional-1', 'Encourages development of townhomes, condominiums, apartment buildings, and mixed-use buildings appropriately scaled to the corridor. Facilitates conversion of single-family homes to offices or limited retail. Aims to provide affordable workforce housing and buffer adjacent single-family neighborhoods from traffic.', 36, NULL, NULL, NULL, NULL, 'Parking, detention and retention ponds, drainage ditches, and accessory structures shall be located behind the principal building to the rear of the property.', NULL, 'Access to parking shall be designed to take advantage of the first available alternative, with alley or secondary street access preferred (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'crt-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Townhomes', 'Condominiums', 'Apartment buildings', 'Mixed-use buildings', 'Offices (conversion from single-family homes)', 'Limited retail uses (conversion from single-family homes)', 'Workforce housing') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'CCT-1', 'cct-1', 'Corridor Commercial Traditional-1', 'Protects the traditional commercial character of these corridors while permitting rehabilitation, improvement, and redevelopment in a manner that encourages walkable streetscapes. Generally allows one-story to three-story development containing mixed uses with multifamily structures.', 42, NULL, NULL, NULL, 0, NULL, NULL, 'Access to parking shall be from the street. Driveway shall serve the entire complex, not individual units, and shall not exceed one lane in each direction (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cct-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Mixed uses with multifamily structures', 'Residential uses', 'Commercial uses', 'Workforce housing (with additional density)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'CCT-2', 'cct-2', 'Corridor Commercial Traditional-2', 'Protects the traditional commercial character of these corridors, encouraging walkable streetscapes. Generally allows one to five-story development containing mixed uses with multifamily structures.', NULL, NULL, NULL, NULL, 0, NULL, 'No fence or wall shall be installed within three feet of any wall on an adjoining property if such wall has one or more windows or doors.', 'Access to parking shall be made from the alley or secondary roadway. No new curb cuts shall be allowed on Central Avenue (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cct-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Mixed uses with multifamily structures', 'Multifamily uses', 'Commercial uses', 'Workforce housing (with additional density)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'IT', 'it', 'Industrial Traditional', 'Designated for traditional industrial uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to the Use Permissions and Parking Requirements Matrix (Section 16.10.020.1).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'it' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Industrial uses', 'Accessory uses and structures (not limited to 67% of principal use)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'IS', 'is', 'Industrial Suburban', 'Designated for suburban industrial uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to the Use Permissions and Parking Requirements Matrix (Section 16.10.020.1).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'is' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Industrial uses', 'Accessory uses and structures (not limited to 67% of principal use)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'st-petersburg'), 'DC-1', 'dc-1', 'Downtown Center-1', 'Promotes redevelopment and a vibrant community center. Allows a variety of nonresidential uses complemented by residential uses at urban densities, supporting a pedestrian-oriented environment. Intended for both multiple-family residential and commercial uses, including small-scale office and service uses compatible with medium to medium-high density residential.', 55, NULL, NULL, NULL, 4, NULL, 12, 'Parking minimums for residential units in the downtown core with 750 sq ft or less were eliminated (specifics in Use Permissions and Parking Requirements Matrix).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'dc-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'st-petersburg') AND pu.name IN ('Multiple-family residential', 'Commercial uses', 'Small-scale office', 'Service uses') ON CONFLICT DO NOTHING;
