-- Gemini-extracted: Jacksonville, FL
-- Generated: 2026-04-07T23:05:13.196Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Florida', 'florida', 'FL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'florida'), 'Duval County', 'duval-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'duval-county' AND state_id = (SELECT id FROM states WHERE slug = 'florida')), 'Jacksonville', 'jacksonville', 30.3322, -81.6557, 949611) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mobile homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Foster care homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community residential homes (6 or fewer residents)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Family day care homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Essential services (water, sewer, gas, telephone, radio, television, electric)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Golf courses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood parks, pocket parks, playgrounds, recreational structures', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Country clubs', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Animals (other than household pets)', 'Agricultural') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home occupations', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cemeteries and mausoleums (by exception, no funeral homes)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Schools (meeting specific standards)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory uses (detached garages, sheds)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family dwellings (apartments, condominiums)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical and dental or chiropractor offices and clinics (not hospitals)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional and business offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family residential (vertically integrated with ground floor permitted use)', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood retail sales and service establishments (individual building footprint <= 40,000 sqft)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service establishments (barber/beauty shops, shoe repair)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants (without drive-in/drive-through)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Banks (without drive-thru tellers) and financial institutions, travel agencies', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Libraries, museums, community centers', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automated Car Washes/Auto Laundry (meeting performance standards)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical and dental office or clinics (not hospitals)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwellings (pre-Comprehensive Plan)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Schools, vocational/trade/business schools, colleges and universities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Fraternity and sorority houses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks, playgrounds, playfields, recreational/community structures', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Adult Congregate Living Facility', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Radio and television broadcasting studios and offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Banks (without drive-through), savings and loan institutions', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Art galleries, dance, art, gymnastics, fitness centers, martial arts, music studios, theaters for stage performances (not motion picture theaters)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cosmetology and similar uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bed and breakfast establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants (on-premises alcohol only, seating limits)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community residential homes (up to 6 residents)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hospice facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Employment office (not day labor pool)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cottages', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial retail sales and service establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Banks (including drive-thru tellers), loan companies, mortgage brokers, stockbrokers', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('All types of professional and business offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotels and motels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial indoor recreational or entertainment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail outlets for food, drugs, apparel, toys, books, jewelry, art, cameras, sporting goods, hobby shops, pet shops, musical instruments, florists, delicatessens, bakeries, home furnishings, office equipment, antiques, hardware, new automobile parts', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service establishments (barber/beauty shops, shoe repair, restaurants, interior decorators, reducing salons/gymnasiums, self-service laundries/dry cleaners, tailors/dressmakers, laundries/dry cleaning pickup stations, dry cleaning/laundry package plants, radio/television broadcasting offices/studios, communication antennas/towers, funeral homes, marinas, blueprinting, job printing, radio/television repair shops, travel agencies, employment offices, home equipment rental)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Establishments with retail sale and service of alcoholic beverages (on-premises or off-premises)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bottle clubs', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential treatment facilities and emergency shelters', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Crematories', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service stations, service garages for minor repairs, car washes', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Marinas', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Specialty retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('High-rise residential development', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use developments', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Outdoor commercial or recreational activity (with permit)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Personal property storage establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial Surface Parking Lot', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Filling or Fueling Stations (fewer than 8 fueling stations)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service garage for minor repairs (no outdoor storage, bays not facing public right-of-way)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Auto laundry', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Thrift stores (retail outlets for used goods)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day Labor pool (activities within enclosed facility)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Permanent or restricted outside sale and service of food and beverages (including alcohol)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesaling, warehousing, storage or distribution establishments', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing, processing (including food processing but not slaughterhouse), packaging or fabricating', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Printing, publishing or similar establishments', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business and professional offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service establishments catering to commerce and industry', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light assembly and manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing of paints, enamels and allied products', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Concrete batching plants', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research and development activities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Transportation terminals (including freight terminals)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Radio/T.V. studios, transmission and relay towers', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Yard waste composting, recycling facilities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical clinics, veterinary offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Vocational/trade schools and building trade contractors', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Railroad yards, truck terminals, bus and rail stations', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Solid waste management facilities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Institutional uses and public facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Utility plants and facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Transmission and relay towers', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mining', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy manufacturing, repair, fabrication, assembly, packaging, processing, distribution', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Transportation operations, railroad switching yards', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Solid waste management facilities (including composting and recycling operations)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Utility plants', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing, processing, storage or transportation of paper and pulp, scrap metal, explosives, paint, oil, turpentine, shellac, lacquer or varnish and similar other hazardous and toxic materials', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Petroleum refining (including components and raw materials)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Uses engaged in the basic processing and manufacturing of materials or products predominantly from extracted or raw materials', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Storage of, or manufacturing processes using flammable or explosive materials', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Storage or manufacturing processes that potentially involve hazardous conditions', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Operation, parking, and maintenance of vehicles, cleaning of equipment or work processes involving solvents, solid waste or sanitary waste transfer stations, recycling establishments, truck terminals, public works yards, and container storage', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('All public facilities and non-residential uses permitted in residential and commercial land use categories (except public schools)', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'RR-Acre', 'rr-acre', 'Residential Rural-Acre District', 'This district provides rural estate residential opportunities, primarily for single-family dwellings and mobile homes on large lots in suburban and rural areas of the City.', 35, NULL, 43560, 25, 25, 10, 10, 'Two spaces per single-family dwelling.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rr-acre' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Single-family dwellings', 'Mobile homes', 'Foster care homes', 'Community residential homes (6 or fewer residents)', 'Family day care homes', 'Essential services (water, sewer, gas, telephone, radio, television, electric)', 'Churches', 'Golf courses', 'Neighborhood parks, pocket parks, playgrounds, recreational structures', 'Country clubs', 'Animals (other than household pets)', 'Home occupations') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'RLD-60', 'rld-60', 'Residential Low Density-60 District', 'This district is designed for low-density residential living, primarily allowing single-family homes to promote a spacious neighborhood environment.', 35, NULL, 6000, 50, 20, 10, 5, 'Two spaces per single-family dwelling.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rld-60' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Single-family dwellings', 'Cemeteries and mausoleums (by exception, no funeral homes)', 'Schools (meeting specific standards)', 'Parks', 'Accessory uses (detached garages, sheds)', 'Foster care homes', 'Family day care homes', 'Community residential homes (6 or fewer residents)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'RHD-A', 'rhd-a', 'Residential High Density-A District', 'This district supports higher density housing like apartments and condominiums, fitting urban areas needing diverse housing options.', 45, NULL, NULL, NULL, 25, 40, 40, 'Two spaces per townhome or condominium unit, plus one guest space per three units.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rhd-a' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Multi-family dwellings (apartments, condominiums)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'CO', 'co', 'Commercial Office District', 'This district focuses on office buildings and professional services, often serving as a transition between residential and more intensive commercial areas.', 60, NULL, 7500, 50, 10, 10, 0, 'Three spaces per 1,000 square feet of gross floor area for professional and business offices (maximum six spaces per 1,000 sqft). Child or adult care centers limited to 150 children/adults.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'co' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Medical and dental or chiropractor offices and clinics (not hospitals)', 'Professional and business offices', 'Multi-family residential (vertically integrated with ground floor permitted use)', 'Neighborhood retail sales and service establishments (individual building footprint <= 40,000 sqft)', 'Service establishments (barber/beauty shops, shoe repair)', 'Restaurants (without drive-in/drive-through)', 'Banks (without drive-thru tellers) and financial institutions, travel agencies', 'Libraries, museums, community centers', 'Automated Car Washes/Auto Laundry (meeting performance standards)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'CN', 'cn', 'Commercial Neighborhood District', 'This district permits retail uses, office commercial uses, and service establishments that serve the daily needs of contiguous residential neighborhoods.', 60, NULL, 7500, 50, 10, 10, 0, 'One space per 250 square feet of retail space. Child or adult care centers limited to 150 children/adults.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cn' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Medical and dental or chiropractor offices and clinics (not hospitals)', 'Professional and business offices', 'Multi-family residential (vertically integrated with ground floor permitted use)', 'Neighborhood retail sales and service establishments (individual building footprint <= 40,000 sqft)', 'Service establishments (barber/beauty shops, shoe repair)', 'Restaurants (without drive-in/drive-through)', 'Banks (without drive-thru tellers) and financial institutions, travel agencies', 'Libraries, museums, community centers', 'Automated Car Washes/Auto Laundry (meeting performance standards)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'CRO', 'cro', 'Commercial, Residential and Office District', 'This district permits a mix of medical and professional offices, multiple-family dwellings, and limited retail/service establishments, often serving as a transition area.', 45, NULL, 7000, 50, 20, 20, 10, 'Three spaces per 1,000 square feet of gross floor area for professional and business offices (maximum six spaces per 1,000 sqft). Two spaces per multiple-family dwelling unit, plus one guest space per three units. Child or adult care centers limited to 150 children/adults.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cro' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Medical and dental office or clinics (not hospitals)', 'Professional and business offices', 'Multiple-family dwellings', 'Single-family dwellings (pre-Comprehensive Plan)', 'Schools, vocational/trade/business schools, colleges and universities', 'Fraternity and sorority houses', 'Churches', 'Parks, playgrounds, playfields, recreational/community structures', 'Adult Congregate Living Facility', 'Libraries, museums, community centers', 'Radio and television broadcasting studios and offices', 'Banks (without drive-through), savings and loan institutions', 'Art galleries, dance, art, gymnastics, fitness centers, martial arts, music studios, theaters for stage performances (not motion picture theaters)', 'Cosmetology and similar uses', 'Bed and breakfast establishments', 'Restaurants (on-premises alcohol only, seating limits)', 'Community residential homes (up to 6 residents)', 'Hospice facilities', 'Employment office (not day labor pool)', 'Cottages') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'CCG-1', 'ccg-1', 'Commercial Community/General-1 District', 'This district allows a wide range of retail sales and services, including general merchandise, apparel, food, and related items, as well as offices and highway commercial uses.', 60, NULL, NULL, NULL, NULL, 10, 0, 'One space per 300 square feet of gross floor area for most retail establishments.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ccg-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Commercial retail sales and service establishments', 'Banks (including drive-thru tellers), loan companies, mortgage brokers, stockbrokers', 'All types of professional and business offices', 'Hotels and motels', 'Commercial indoor recreational or entertainment', 'Retail outlets for food, drugs, apparel, toys, books, jewelry, art, cameras, sporting goods, hobby shops, pet shops, musical instruments, florists, delicatessens, bakeries, home furnishings, office equipment, antiques, hardware, new automobile parts', 'Service establishments (barber/beauty shops, shoe repair, restaurants, interior decorators, reducing salons/gymnasiums, self-service laundries/dry cleaners, tailors/dressmakers, laundries/dry cleaning pickup stations, dry cleaning/laundry package plants, radio/television broadcasting offices/studios, communication antennas/towers, funeral homes, marinas, blueprinting, job printing, radio/television repair shops, travel agencies, employment offices, home equipment rental)', 'Establishments with retail sale and service of alcoholic beverages (on-premises or off-premises)', 'Bottle clubs', 'Residential treatment facilities and emergency shelters', 'Crematories', 'Service stations, service garages for minor repairs, car washes') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'CCBD', 'ccbd', 'Commercial Central Business District', 'This is a high-density mixed-use area intended to promote revitalization and growth in downtown, ensuring compatibility between new and existing uses, and promoting access to the St. Johns River. It is the single zoning district for almost all Downtown properties (excluding PUDs).', NULL, NULL, NULL, 95, NULL, NULL, NULL, 'No off-street parking required for dwelling units in existing nonresidential structures; one space per dwelling unit for new construction. For other uses, three spaces per 1,000 square feet of gross floor area (maximum six spaces per 1,000 sqft).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ccbd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Marinas', 'Parks', 'Hotel', 'Commercial office', 'Specialty retail', 'High-rise residential development', 'Mixed-use developments', 'Outdoor commercial or recreational activity (with permit)', 'Personal property storage establishments', 'Commercial Surface Parking Lot', 'Filling or Fueling Stations (fewer than 8 fueling stations)', 'Service garage for minor repairs (no outdoor storage, bays not facing public right-of-way)', 'Auto laundry', 'Thrift stores (retail outlets for used goods)', 'Day Labor pool (activities within enclosed facility)', 'Permanent or restricted outside sale and service of food and beverages (including alcohol)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'IL', 'il', 'Industrial Light District', 'This district permits light industrial uses, offices, public facilities, and supporting retail commercial uses with fewer objectionable impacts such as noise, odor, toxic chemicals, and wastes.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One space per 2,000 square feet of gross floor area for industrial, wholesale, warehouse, storage, and similar uses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'il' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Wholesaling, warehousing, storage or distribution establishments', 'Light manufacturing, processing (including food processing but not slaughterhouse), packaging or fabricating', 'Printing, publishing or similar establishments', 'Business and professional offices', 'Service establishments catering to commerce and industry', 'Light assembly and manufacturing', 'Manufacturing of paints, enamels and allied products', 'Concrete batching plants', 'Research and development activities', 'Transportation terminals (including freight terminals)', 'Radio/T.V. studios, transmission and relay towers', 'Yard waste composting, recycling facilities', 'Medical clinics, veterinary offices', 'Vocational/trade schools and building trade contractors', 'Railroad yards, truck terminals, bus and rail stations', 'Solid waste management facilities', 'Institutional uses and public facilities', 'Utility plants and facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'jacksonville'), 'IH', 'ih', 'Industrial Heavy District', 'This district generally involves creating or utilizing materials or products predominantly from extracted or raw materials, or activities that potentially involve hazardous or commonly recognized offensive conditions. It is the most likely to produce adverse physical and environmental impacts.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One space per 2,000 square feet of gross floor area for industrial, wholesale, warehouse, storage, and similar uses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ih' AND z.city_id = (SELECT id FROM cities WHERE slug = 'jacksonville') AND pu.name IN ('Research and development activities', 'Transmission and relay towers', 'Mining', 'Heavy manufacturing, repair, fabrication, assembly, packaging, processing, distribution', 'Transportation operations, railroad switching yards', 'Solid waste management facilities (including composting and recycling operations)', 'Utility plants', 'Manufacturing, processing, storage or transportation of paper and pulp, scrap metal, explosives, paint, oil, turpentine, shellac, lacquer or varnish and similar other hazardous and toxic materials', 'Petroleum refining (including components and raw materials)', 'Uses engaged in the basic processing and manufacturing of materials or products predominantly from extracted or raw materials', 'Storage of, or manufacturing processes using flammable or explosive materials', 'Storage or manufacturing processes that potentially involve hazardous conditions', 'Operation, parking, and maintenance of vehicles, cleaning of equipment or work processes involving solvents, solid waste or sanitary waste transfer stations, recycling establishments, truck terminals, public works yards, and container storage', 'All public facilities and non-residential uses permitted in residential and commercial land use categories (except public schools)') ON CONFLICT DO NOTHING;
