-- Gemini-extracted: Tampa, FL
-- Generated: 2026-04-07T23:07:33.250Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Florida', 'florida', 'FL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'florida'), 'Hillsborough County', 'hillsborough-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'hillsborough-county' AND state_id = (SELECT id FROM states WHERE slug = 'florida')), 'Tampa', 'tampa', 27.9506, -82.4572, 384959) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory Dwelling Unit (ADU)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood shopping center (special exception)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automotive sales and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bed and breakfast', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bus shelters', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Motion picture studio', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Open storage and processing areas (with buffering and screening)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Food Processing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Handicraft Industry', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small Industry (<=10,000 sq ft)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research and Development, General', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing, Small (<=10,000 sq ft)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesaling', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwelling types', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood scale office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood scale commercial', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use developments', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'RS-50', 'rs-50', 'Residential Single-Family 50', 'This district provides areas for primarily low-density single-family detached dwellings with smaller minimum lot size requirements, aiming to maintain neighborhood character.', NULL, NULL, 5000, NULL, 20, 7, 7, 'Accessory dwelling units greater than 600 square feet require 1 off-street parking space.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-50' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Single-family detached dwelling', 'Accessory Dwelling Unit (ADU)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'RS-75', 'rs-75', 'Residential Single-Family 75', 'This district designates areas for single-family detached dwellings with specific lot size and setback requirements.', NULL, NULL, 7500, NULL, 20, 15, 12, 'Accessory dwelling units greater than 600 square feet require 1 off-street parking space.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-75' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Single-family detached dwelling', 'Accessory Dwelling Unit (ADU)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'RM-24', 'rm-24', 'Residential Multi-Family 24', 'This district is intended for multi-family residential developments, allowing for moderate to high-density housing.', NULL, NULL, NULL, NULL, 25, 20, 7, 'One (1) loading berth minimum for multiple family projects. Parking structures accessory to principal residential use are permitted if they meet area, height, bulk, and placement regulations.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-24' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Multi-family dwellings', 'Single-family attached dwellings') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'RM-50', 'rm-50', 'Residential Multi-Family 50', 'This district accommodates multi-family residential uses, with regulations that may include increased side setbacks for taller buildings.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One (1) loading berth minimum for multiple family projects. Parking structures accessory to principal residential use are permitted if they meet area, height, bulk, and placement regulations.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-50' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Multi-family dwellings') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'CN', 'cn', 'Commercial Neighborhood', 'This district is intended for neighborhood-oriented commercial uses, with specific requirements for landscaping and setbacks when adjacent to residential areas.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'For non-residential development, 1 space per 2,500 square feet, with structures under 1,500 gross floor area not required to provide parking.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cn' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Neighborhood shopping center (special exception)', 'Retail establishments', 'Office uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'CG', 'cg', 'Commercial General', 'This district defines and controls major pedestrian-oriented shopping and business areas, with regulations that may include increased side setbacks for taller buildings.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Most retail establishments require 1 parking space per 250 square feet of gross floor area; shopping centers require 4 spaces per 1,000 square feet of gross leasable area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cg' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Automotive sales and services', 'Bed and breakfast', 'Bus shelters', 'Retail', 'Office') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'IH', 'ih', 'Industrial Heavy', 'This district is designed to accommodate heavy industrial uses and activities that may generate significant negative environmental impacts, requiring careful consideration of location and buffering.', NULL, NULL, 10000, 75, NULL, NULL, NULL, 'Parking requirements for industrial uses are generally based on specific use categories.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ih' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Motion picture studio', 'Open storage and processing areas (with buffering and screening)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'IG', 'ig', 'Industrial General', 'This district provides an area suitable for a wide range of moderate to low-intensity industrial uses, including light manufacturing and research and development.', 175, NULL, 200000, 50, 50, 15, 15, 'Parking requirements for industrial uses are generally based on specific use categories.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ig' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Food Processing', 'Handicraft Industry', 'Small Industry (<=10,000 sq ft)', 'Research and Development, General', 'Warehousing, Small (<=10,000 sq ft)', 'Wholesaling') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'NMU-16', 'nmu-16', 'Neighborhood Mixed Use 16', 'This district allows for mixed-use development at a neighborhood scale, including residential, office, and commercial uses, within designated Urban Villages.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Local governments must consider reducing parking for such developments. Mixed-use qualifying developments with surface or structured parking less than six stories may provide 20% greenspace.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nmu-16' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Single-family dwelling types', 'Neighborhood scale office', 'Neighborhood scale commercial') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'tampa'), 'CBD-1', 'cbd-1', 'Central Business District 1', 'This sub-district is appropriate for a variety of residential, office, commercial, and mixed-use developments with an urban, pedestrian, and transit-oriented pattern, typically in the northern areas of the Central Business District.', 120, NULL, NULL, NULL, NULL, NULL, NULL, 'Properties within Tampa''s Central Business District have reduced parking requirements or special ratios.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cbd-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'tampa') AND pu.name IN ('Residential', 'Office', 'Commercial', 'Mixed-use developments') ON CONFLICT DO NOTHING;
