-- Gemini-extracted: Miami, FL
-- Generated: 2026-04-07T23:06:35.620Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Florida', 'florida', 'FL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'florida'), 'Miami-Dade County', 'miami-dade-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'miami-dade-county' AND state_id = (SELECT id FROM states WHERE slug = 'florida')), 'Miami', 'miami', 25.7617, -80.1918, 442241) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single Family Residence', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two Family Residence', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential Uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Lodging', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Entertainment Establishment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Food Service Establishment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Place of Assembly', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Recreational Establishment', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Religious Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Alcohol Beverage Service Establishment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('General Commercial', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Marine Related Commercial Establishment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Open Air Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily Housing', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dormitory', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live-Work', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Work-Live', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bed & Breakfast', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Inn', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial Auto-Related', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Regional Activity Complex', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Civil Support', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Support Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial Uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Playground', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Garden, Small', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Garden, Medium', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Garden, Large', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Recreational Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'T3-R', 't3-r', 'Sub-Urban Transect Zone - Restricted', 'Low-density areas, primarily comprised of single-family residential units with relatively deep setbacks.', 25, NULL, 5000, 75, 20, 20, 5, 'Minimum of 1.5 parking spaces per principal dwelling unit; tandem parking encouraged.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't3-r' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Single Family Residence') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'T3-L', 't3-l', 'Sub-Urban Transect Zone - Limited', 'Low-density areas, primarily comprised of single-family and two-family residential units with relatively deep setbacks.', 25, NULL, 5000, 75, 20, 20, 5, 'Minimum of 1.5 parking spaces per principal dwelling unit; tandem parking encouraged.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't3-l' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Single Family Residence', 'Two Family Residence') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'T4-L', 't4-l', 'General Urban Transect Zone - Limited', 'Medium-density areas allowing for small multi-family buildings and mixed-use developments.', 42, NULL, 1400, 85, 10, 20, 0, 'Vehicular parking and loading required as shown in Article 4, Tables 4 and 5; minimum of 1 bicycle rack space for every 20 vehicular parking spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't4-l' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Residential Uses', 'Lodging', 'Office', 'Commercial', 'Entertainment Establishment', 'Food Service Establishment', 'Place of Assembly', 'Recreational Establishment', 'Community Facility', 'Religious Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'T4-O', 't4-o', 'General Urban Transect Zone - Open', 'Medium-density areas allowing for small multi-family buildings and mixed-use developments with more flexibility than T4-L.', 42, NULL, 1400, 85, 10, 20, 0, 'Vehicular parking and loading required as shown in Article 4, Tables 4 and 5; minimum of 1 bicycle rack space for every 20 vehicular parking spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't4-o' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Residential Uses', 'Lodging', 'Office', 'Commercial', 'Entertainment Establishment', 'Food Service Establishment', 'Place of Assembly', 'Recreational Establishment', 'Community Facility', 'Religious Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'T5-L', 't5-l', 'Urban Center Transect Zone - Limited', 'Urban Center Zones are characterized by a mix of residential, commercial, and civic uses, with higher densities and intensities than T4 zones.', 70, NULL, 1200, 90, 10, 0, 0, 'Vehicular parking and loading required as shown in Article 4, Tables 4 and 5; on-street parking may count.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't5-l' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Residential Uses', 'Lodging', 'Office', 'Commercial', 'Entertainment Establishment', 'Food Service Establishment', 'Alcohol Beverage Service Establishment', 'General Commercial', 'Marine Related Commercial Establishment', 'Open Air Retail', 'Place of Assembly', 'Recreational Establishment', 'Community Facility', 'Religious Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'T6-8', 't6-8', 'Urban Core Transect Zone - 8 Stories', 'High-density mixed-use areas, prioritizing the built environment with a wide array of uses and building types.', 112, 5, 5000, 90, 0, 0, 0, 'Minimum of 1.5 parking spaces per principal dwelling unit; parking may be reduced near transit; small buildings less than 10,000 sq ft may not require parking.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't6-8' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Single Family Residence', 'Multifamily Housing', 'Dormitory', 'Live-Work', 'Work-Live', 'Bed & Breakfast', 'Inn', 'Hotel', 'Office', 'Commercial Auto-Related', 'Entertainment Establishment', 'Food Service Establishment', 'Alcohol Beverage Service Establishment', 'General Commercial', 'Marine Related Commercial Establishment', 'Open Air Retail', 'Place of Assembly', 'Recreational Establishment', 'Community Facility', 'Religious Facility', 'Regional Activity Complex', 'Civil Support', 'Community Support Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'D1', 'd1', 'Workplace District Zone', 'Prioritizes the built environment, primarily for commercial and office uses. Mezzanines may be 50% of floor area.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Vehicular parking and loading required as shown in Article 4, Tables 4 and 5.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Office', 'Commercial', 'Entertainment Establishment', 'Food Service Establishment', 'Alcohol Beverage Service Establishment', 'General Commercial', 'Marine Related Commercial Establishment', 'Open Air Retail', 'Place of Assembly', 'Recreational Establishment', 'Community Facility', 'Religious Facility', 'Regional Activity Complex', 'Civil Support', 'Community Support Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'D2', 'd2', 'Industrial District Zone', 'Prioritizes the built environment, for industrial uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Vehicular parking and loading required as shown in Article 4, Tables 4 and 5.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Industrial Uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'CS', 'cs', 'Civic Space Zone', 'Consists of public open spaces.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N/A.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cs' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Playground', 'Community Garden, Small', 'Community Garden, Medium', 'Community Garden, Large', 'Community Facility', 'Recreational Facility', 'Religious Facility', 'Regional Activity Complex', 'Civil Support', 'Community Support Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'miami'), 'CI', 'ci', 'Civic Institution Zone', 'Consists of public and semi-public institutional uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Vehicular parking and loading required as shown in Article 4, Tables 4 and 5; density of abutting zone.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ci' AND z.city_id = (SELECT id FROM cities WHERE slug = 'miami') AND pu.name IN ('Community Facility', 'Recreational Facility', 'Religious Facility', 'Regional Activity Complex', 'Civil Support', 'Community Support Facility') ON CONFLICT DO NOTHING;
