-- Gemini-extracted: Naperville, IL
-- Generated: 2026-04-07T23:17:25.068Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Illinois', 'illinois', 'IL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'illinois'), 'DuPage County', 'dupage-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'dupage-county' AND state_id = (SELECT id FROM states WHERE slug = 'illinois')), 'Naperville', 'naperville', 41.7508, -88.1535, 149540) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Primary and secondary schools (without boarding facilities)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Preschools (accessory to primary/secondary schools)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Golf courses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks, playgrounds, and forest preserves', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential care homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Any use permitted in the R1A district', 'Residential|Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family dwellings and duplexes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bakeries', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Banks and financial institutions', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Barbershops and beauty shops/salons', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bookstores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Coffee shops', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Drugstores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Grocery stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants (without drive-through)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automobile service stations', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business and professional offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotels and motels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants (with or without drive-through)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Theaters', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Eating and drinking establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial services (banks, beauty shops/salons, dry cleaning)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices (on upper stories)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses (on upper stories)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hospitals', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Nursery schools, preschools, daycare centers and student learning centers', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices—Business or professional', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Veterinary offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Fitness facility', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Laboratories (research, experimental, and testing)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing and assembly', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Vocational and trade schools', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouse and storage facilities (accessory, less than 50% of building GFA)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing uses (accessory, less than 50% of building GFA)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Abrasive manufacture', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automobile repair facilities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Building material sales and storage', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing and distribution centers', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'R1A', 'r1a', 'Low Density Single-Family Residence District', 'This district is intended to provide for low density single-family residential development and to accommodate various public and recreational uses.', 35, NULL, 10000, 40, 30, 30, 6, 'Refer to Chapter 9 of the Naperville Municipal Code; for single-family detached dwellings, 2 spaces per dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r1a' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Single-family detached dwellings', 'Primary and secondary schools (without boarding facilities)', 'Preschools (accessory to primary/secondary schools)', 'Golf courses', 'Parks, playgrounds, and forest preserves', 'Residential care homes') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'R1B', 'r1b', 'Medium Density Single-Family Residence District', 'This district is intended to provide for medium density single-family residential development and to accommodate various public and recreational uses.', 35, NULL, 7200, 45, 30, 30, 6, 'Refer to Chapter 9 of the Naperville Municipal Code; for single-family detached dwellings, 2 spaces per dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r1b' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Single-family detached dwellings', 'Primary and secondary schools (without boarding facilities)', 'Preschools (accessory to primary/secondary schools)', 'Golf courses', 'Parks, playgrounds, and forest preserves', 'Residential care homes') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'R2', 'r2', 'Single-Family and Low Density Multiple-Family Residence District', 'The R2 district is intended to provide multiple-family areas of a low density character accommodating a variety of housing types and compatible uses.', 35, NULL, 7200, 50, 30, 30, 6, 'Refer to Chapter 9 of the Naperville Municipal Code; for single-family and two-family dwellings, 2 spaces per dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Any use permitted in the R1A district', 'Two-family dwellings and duplexes') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'B1', 'b1', 'Neighborhood Convenience Shopping Center District', 'This district is intended to provide for the retailing of convenience goods and the furnishing of personal services to meet the daily needs of residents of adjacent residential areas.', 35, NULL, 20000, 75, 30, 30, 15, 'Refer to Chapter 9 of the Naperville Municipal Code; e.g., Retail stores: 1 space per 250 sq ft of gross floor area; Restaurants: 1 space per 100 sq ft of gross floor area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Bakeries', 'Banks and financial institutions', 'Barbershops and beauty shops/salons', 'Bookstores', 'Coffee shops', 'Drugstores', 'Grocery stores', 'Restaurants (without drive-through)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'B3', 'b3', 'General Commercial District', 'This district is intended to provide for a wide range of commercial activities, including retail, service, and office uses, serving a broader market area.', 45, NULL, 20000, 80, 30, 30, 15, 'Refer to Chapter 9 of the Naperville Municipal Code; e.g., Retail stores: 1 space per 250 sq ft of gross floor area; Restaurants: 1 space per 100 sq ft of gross floor area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Automobile service stations', 'Banks and financial institutions', 'Business and professional offices', 'Hotels and motels', 'Retail stores', 'Restaurants (with or without drive-through)', 'Theaters') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'B4', 'b4', 'Downtown Core District', 'This district is intended to accommodate the retail, service, and office uses that comprise the central business district, with an emphasis on pedestrian activity.', 60, NULL, NULL, 100, 6, NULL, NULL, 'Refer to Chapter 9 of the Naperville Municipal Code; often reduced or shared parking in downtown areas.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Retail stores', 'Eating and drinking establishments', 'Commercial services (banks, beauty shops/salons, dry cleaning)', 'Offices (on upper stories)', 'Residential uses (on upper stories)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'OCI', 'oci', 'Office, Commercial and Institutional District', 'This district is intended to provide for office, commercial, and institutional uses in a campus-like setting, with an emphasis on professional services and limited retail.', 45, NULL, 20000, 75, 30, 30, 15, 'Refer to Chapter 9 of the Naperville Municipal Code; e.g., Offices: 1 space per 300 sq ft of gross floor area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'oci' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Banks and financial institutions', 'Hospitals', 'Nursery schools, preschools, daycare centers and student learning centers', 'Offices—Business or professional', 'Veterinary offices', 'Fitness facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'RD', 'rd', 'Research and Development District', 'This district is intended to provide for research, development, and limited manufacturing activities in a high-quality, campus-like environment.', 45, NULL, 40000, 75, 50, 30, 25, 'Refer to Chapter 9 of the Naperville Municipal Code; e.g., Industrial/Manufacturing: 1 space per 500 sq ft of gross floor area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Banks and financial institutions', 'Business and professional offices', 'Laboratories (research, experimental, and testing)', 'Light manufacturing and assembly', 'Vocational and trade schools') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'ORI', 'ori', 'Office, Research and Light Industry District', 'This district is intended to provide for a mix of uses directed toward research and development activities, engineering and testing activities, and office uses while accommodating accessory warehouse and storage facilities and manufacturing uses.', 45, NULL, 40000, 80, 50, 30, 25, 'Refer to Chapter 9 of the Naperville Municipal Code; e.g., Industrial/Manufacturing: 1 space per 500 sq ft of gross floor area; Offices: 1 space per 300 sq ft of gross floor area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ori' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Business and professional offices', 'Laboratories (research, experimental, and testing)', 'Light manufacturing and assembly', 'Warehouse and storage facilities (accessory, less than 50% of building GFA)', 'Manufacturing uses (accessory, less than 50% of building GFA)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'naperville'), 'I', 'i', 'Industrial District', 'This district is intended to provide for general industrial uses, including manufacturing, processing, and warehousing, with appropriate performance standards.', 60, NULL, 40000, 85, 50, 30, 25, 'Refer to Chapter 9 of the Naperville Municipal Code; e.g., Industrial/Manufacturing: 1 space per 500 sq ft of gross floor area.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'i' AND z.city_id = (SELECT id FROM cities WHERE slug = 'naperville') AND pu.name IN ('Abrasive manufacture', 'Automobile repair facilities', 'Building material sales and storage', 'Heavy manufacturing', 'Warehousing and distribution centers') ON CONFLICT DO NOTHING;
