-- Gemini-extracted: Chicago, IL
-- Generated: 2026-04-07T23:15:56.166Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Illinois', 'illinois', 'IL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'illinois'), 'Cook County', 'cook-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'cook-county' AND state_id = (SELECT id FROM states WHERE slug = 'illinois')), 'Chicago', 'chicago', 41.8781, -87.6298, 2746388) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Detached House', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-flat (conditional)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-flat', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouse', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Low-density multi-unit residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-unit residential building', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail storefronts', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Artist Live/Work Space (above ground floor)', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Shopping centers', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Large retail stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling units (above ground floor)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Auto-oriented commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Low-impact manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesaling', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Distribution activities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory retail sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Car Wash or Cleaning Service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Moderate-impact manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Outdoor storage and work-related activities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('High-density residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'RS-3', 'rs-3', 'Residential Single-Unit (Detached House) District', 'Primarily for detached single-family homes, with provisions for two-flats under specific conditions, maintaining the character of single-unit neighborhoods.', 30, 0.9, 2500, NULL, 20, 35, 5, '2 spaces per unit for detached houses; 1.5 spaces per unit for two-flats, with exemptions for lots 33 feet or less in width without alley access.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Detached House', 'Two-flat (conditional)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'RT4', 'rt4', 'Residential Two-Flat, Townhouse and Multi-Unit District', 'Accommodates detached houses, two-flats, townhouses, and low-density multi-unit residential buildings, providing a transition between single-unit and higher-density residential districts.', 38, 1.2, 1000, NULL, 15, NULL, NULL, '1 space per unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rt4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Detached House', 'Two-flat', 'Townhouse', 'Low-density multi-unit residential') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'RM-5', 'rm-5', 'Residential Multi-Unit District', 'Intended for moderate- to high-density multi-unit residential buildings, including detached houses, two-flats, and townhouses, in areas where such development exists or is desired.', 45, 2, 400, NULL, 15, NULL, NULL, '1 space per unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Detached House', 'Two-flat', 'Townhouse', 'Multi-unit residential building') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'B1-2', 'b1-2', 'Neighborhood Shopping District', 'Designed for a broad range of small-scale retail and service uses, often embedded in residential neighborhoods. Setbacks are generally not required unless abutting a residential district.', 38, 2.2, 1000, NULL, NULL, NULL, NULL, 'Typically ranges from 2.5 to 5 spaces per 1,000 square feet of floor area, varying by B classification and store size.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b1-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Retail storefronts', 'Service establishments', 'Artist Live/Work Space (above ground floor)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'B3-3', 'b3-3', 'Community Shopping District', 'The most permissive retail district, accommodating shopping centers and larger buildings, with provisions for dwelling units. Setbacks are generally not required unless abutting a residential district.', NULL, 3, 400, NULL, NULL, NULL, NULL, 'Typically ranges from 2.5 to 5 spaces per 1,000 square feet of floor area, varying by B classification and store size.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b3-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Shopping centers', 'Large retail stores', 'Retail storefronts', 'Dwelling units (above ground floor)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'C1-2', 'c1-2', 'Neighborhood Commercial District', 'Primarily for auto-oriented commercial use types, serving neighborhood commercial needs. Rear setbacks may be required when adjacent to residential districts.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Similar to Business districts, with potential additional provisions for larger retail operations.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c1-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Auto-oriented commercial uses', 'Retail sales', 'Service establishments', 'Artist Live/Work Space (above ground floor)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'C3-3', 'c3-3', 'Commercial, Manufacturing and Employment District', 'Accommodates retail, service, commercial, and manufacturing uses, acting as a buffer between industrial and other districts, with no residential uses permitted.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Similar to Business districts, with potential additional provisions for larger retail operations.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c3-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Retail sales', 'Service establishments', 'Commercial uses', 'Manufacturing uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'M1-2', 'm1-2', 'Limited Manufacturing/Business Park District', 'Intended for low-impact manufacturing, wholesaling, warehousing, and distribution activities primarily within enclosed buildings, promoting high-quality industrial development. Setbacks are generally not required, with exceptions for industrial parks and business parks.', NULL, 2.2, NULL, NULL, NULL, NULL, NULL, 'Off-street parking regulations are detailed in Chapter 17-10 of the Zoning Ordinance.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm1-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Low-impact manufacturing', 'Wholesaling', 'Warehousing', 'Distribution activities', 'Accessory retail sales', 'Car Wash or Cleaning Service') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'M2-3', 'm2-3', 'Light Industry District', 'Accommodates moderate-impact manufacturing, wholesaling, warehousing, and distribution uses, including outdoor storage and work-related activities, generally more land-intensive than M1. Setbacks are generally not required, with exceptions for industrial parks and business parks.', NULL, 3, NULL, NULL, NULL, NULL, NULL, 'Off-street parking regulations are detailed in Chapter 17-10 of the Zoning Ordinance.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm2-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('Moderate-impact manufacturing', 'Wholesaling', 'Warehousing', 'Distribution activities', 'Outdoor storage and work-related activities', 'Accessory retail sales', 'Car Wash or Cleaning Service') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'chicago'), 'DX-5', 'dx-5', 'Downtown Mixed-Use District', 'Designed for high-density mixed-use developments in the downtown core, allowing for the tallest buildings and significant concentrations of residential, commercial, and office uses.', NULL, 5, NULL, NULL, NULL, NULL, NULL, 'Reduced parking requirements to reflect greater public transit access and pedestrian traffic; varies by use and transit proximity.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'dx-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'chicago') AND pu.name IN ('High-density residential', 'Commercial uses', 'Office uses', 'Retail') ON CONFLICT DO NOTHING;
