-- Gemini-extracted: Rockford, IL
-- Generated: 2026-04-07T23:19:41.982Z
-- Zones: 8
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Illinois', 'illinois', 'IL') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'illinois'), 'Winnebago County', 'winnebago-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'winnebago-county' AND state_id = (SELECT id FROM states WHERE slug = 'illinois')), 'Rockford', 'rockford', 42.2711, -89.094, 148655) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private and noncommercial gardens', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory buildings and uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Schools', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Libraries', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Museums', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Art galleries', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Playgrounds', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community centers', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public services', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Utility office buildings', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family manufactured home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Rest homes, nursing homes and convalescent homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private recreational uses and facilities (compatible with residential neighborhood)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public and public utility buildings, structures and uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex and single-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple-family dwellings and dwelling groups', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Boardinghouses and rooming houses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public schools, parochial schools, kindergartens', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public parks and recreational facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches and similar religious institutions', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Developer''s project office and sales office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential facilities', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Low-intensity office development', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Limited business service uses (low traffic generators)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sale of goods', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Broad range of business, service, and commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Uses involving outdoor operations and storage', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Most types of industrial firms', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Higher intensity industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'R-1', 'r-1', 'Single Family Residential Zoning District', 'The R-1 district is intended to accommodate low-density residential uses, primarily single-family detached dwellings, and those public and semi-public uses normally considered an integral part of the residential neighborhood they serve.', 35, NULL, 9000, NULL, 25, 20, 6, 'Two off-street parking spaces, with one parking space in a fully enclosed building.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Single-family detached dwellings', 'Private and noncommercial gardens', 'Accessory buildings and uses', 'Churches', 'Schools', 'Libraries', 'Museums', 'Art galleries', 'Parks', 'Playgrounds', 'Community centers', 'Public services', 'Utility office buildings') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'R-2', 'r-2', 'Residential Two-Family District', 'The purpose of the R-2 district is to promote and encourage a suitable environment for family life at a slightly higher density than that permitted in the R-1 district, and also to provide opportunities for the development of lower cost duplex and attached dwellings.', 35, NULL, 6000, NULL, 20, 10, 6, 'Two parking spaces per dwelling unit for duplexes.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Single-family detached dwellings', 'Single-family manufactured home', 'Rest homes, nursing homes and convalescent homes', 'Private recreational uses and facilities (compatible with residential neighborhood)', 'Public and public utility buildings, structures and uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'R-3', 'r-3', 'Residential Multiple-Family District', 'The R-3 district is intended to provide opportunities for the development of attractive living environments at densities greater than permitted in other residential districts, encouraging high-density development of affordable single-family and multiple-family housing types for both owner and renter occupants.', 35, NULL, 6000, NULL, 20, 10, 6, 'One and one-half spaces per dwelling unit for apartment buildings.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Duplex and single-family attached dwellings', 'Multiple-family dwellings and dwelling groups', 'Boardinghouses and rooming houses', 'Public schools, parochial schools, kindergartens', 'Public parks and recreational facilities', 'Churches and similar religious institutions', 'Developer''s project office and sales office', 'Residential facilities', 'Residential homes') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'C-1', 'c-1', 'Limited Office', 'The C-1, Limited Office district is intended to accommodate low-intensity office development in close proximity to residential uses, serving as a buffer between established commercial uses and residential neighborhoods. It allows the conversion of residential structures to limited office use to preserve them, and permits limited business service uses that are low traffic generators.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One space for each 250 square feet of floor area for offices.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Low-intensity office development', 'Limited business service uses (low traffic generators)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'C-2', 'c-2', 'Limited Commercial', 'The purpose of the C-2, Limited Commercial district is to provide a wide range of development options for the retail sale of goods and for professional and commercial services, while limiting uses that may cause undue traffic congestion or have detrimental impacts on neighboring properties.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One parking space for every 250 square feet of gross floor area for most commercial establishments.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Retail sale of goods', 'Professional services', 'Commercial services') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'C-3', 'c-3', 'General Commercial', 'The C-3, General Commercial district is intended to accommodate a very broad range of business, service, and commercial uses, representing the highest intensity business or commercial zoning district. It allows nearly any type of business, service, or commercial use, including those involving outdoor operations and storage.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One parking space for every 250 square feet of gross floor area for most commercial establishments.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Broad range of business, service, and commercial uses', 'Uses involving outdoor operations and storage') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'I-1', 'i-1', 'Light Industrial', 'The I-1 Light Industrial district is intended to accommodate light industrial uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One space for each two employees, plus one space for each vehicle used in the conduct of the business.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'i-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Light industrial uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rockford'), 'I-2', 'i-2', 'Intensive Industrial District', 'The I-2 Intensive Industrial District is intended to accommodate development by most types of industrial firms, with regulations designed to permit operations in a clean and quiet manner and to protect adjacent uses. It allows higher intensity industrial uses which may have some off-site impacts.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'One space for each two employees, plus one space for each vehicle used in the conduct of the business.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'i-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rockford') AND pu.name IN ('Most types of industrial firms', 'Higher intensity industrial uses') ON CONFLICT DO NOTHING;
