-- Gemini-extracted: Buffalo, NY
-- Generated: 2026-04-07T23:11:50.197Z
-- Zones: 11
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('New York', 'new-york', 'NY') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'new-york'), 'Erie County', 'erie-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'erie-county' AND state_id = (SELECT id FROM states WHERE slug = 'new-york')), 'Buffalo', 'buffalo', 42.8864, -78.8784, 278349) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Civic Building', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial Block', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Stacked Units (Multi-unit dwellings)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Tower', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail & Service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Employment (Offices)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Attached House', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Carriage House', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Shopfront House', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Detached House', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('One-family & Two-family Dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple Unit Dwellings (3 or more)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Gardens', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Market Gardens', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Assembly (Special Use Permit)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bed & Breakfast (Special Use Permit)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public Safety Facilities (Special Use Permit)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood Shops (Special Use Permit)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Group Home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day Care Home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public Safety Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('General Commercial', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-Use', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional or administrative offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Low-impact employment uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Moderate-impact employment uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial, artisan, light', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Recycling facility', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research/laboratory facility', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Storage yard', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouse/distribution', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Freight terminal', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Railway facilities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Truck stop', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('District energy system', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Solar farm', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Utilities and services, major and minor', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wind farm', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Storage units (accessed individually from outside)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Self-storage facility (outdoor storage pods)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Intensive, high-impact employment uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial, artisan, heavy', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Civic greens', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Passive recreational use', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Recreational use', 'Civic') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-1D', 'n-1d', 'Downtown/Regional Hub', 'This zone addresses the core of downtown Buffalo, facilitating substantial development with an intense mix of uses. It is designed for high-density, mixed-use environments.', NULL, NULL, 1000, 100, 0, 0, 0, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-1d' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Civic Building', 'Commercial Block', 'Stacked Units (Multi-unit dwellings)', 'Tower', 'Retail & Service', 'Employment (Offices)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-1C', 'n-1c', 'Mixed-Use Core', 'This zone addresses mixed-use centers of high intensity in strategic locations, such as on the edges of downtown or near light rail transit, often featuring mid-rise buildings.', NULL, NULL, 1000, 100, 0, 0, 0, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-1c' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Attached House', 'Carriage House', 'Civic Building', 'Stacked Units (Multi-unit dwellings)', 'Commercial Block') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-2C', 'n-2c', 'Mixed-Use Center', 'This zone addresses mixed-use, walkable centers of Buffalo''s most compact neighborhoods, many of which were fully developed before the automobile became prominent.', 66, NULL, 1000, 90, 0, 0, 0, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-2c' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Carriage House', 'Civic Building', 'Commercial Block', 'Shopfront House', 'Retail & Service', 'Professional offices') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-2R', 'n-2r', 'Residential', 'This zone addresses residential areas adjoining more intensive mixed-use centers, generally defined by compact residential blocks, which occasionally include small mixed-use buildings.', 76, NULL, 900, 80, 5, 15, 3, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply. Neighborhood Shops require a special use permit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-2r' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Attached House', 'Carriage House', 'Civic Building', 'Detached House', 'Stacked Units (Multi-unit dwellings)', 'One-family & Two-family Dwellings', 'Multiple Unit Dwellings (3 or more)', 'Community Gardens', 'Market Gardens', 'Assembly (Special Use Permit)', 'Bed & Breakfast (Special Use Permit)', 'Public Safety Facilities (Special Use Permit)', 'Neighborhood Shops (Special Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-3R', 'n-3r', 'Residential', 'This zone addresses residential areas adjoining the centers of Buffalo''s streetcar neighborhoods, generally defined by moderately compact residential blocks, which occasionally include small mixed-use buildings.', 40, NULL, 1800, 80, 5, 15, 3, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply. Neighborhood Shops require a special use permit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-3r' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Attached House', 'Carriage House', 'Civic Building', 'Detached House', 'Stacked Units (Multi-unit dwellings)', 'One-family & Two-family Dwellings', 'Multiple Unit Dwellings (3 or more)', 'Community Gardens', 'Market Gardens', 'Assembly (Special Use Permit)', 'Bed & Breakfast (Special Use Permit)', 'Public Safety Facilities (Special Use Permit)', 'Neighborhood Shops (Special Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-4-30', 'n-4-30', 'Single-Family', 'This zone addresses areas composed primarily of single-family homes on moderately compact lots of at least 30 feet in width.', 45, NULL, NULL, 80, NULL, NULL, 3, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-4-30' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Civic Building', 'Detached House', 'Group Home', 'Day Care Home', 'Public Safety Facility', 'Bed & Breakfast (Special Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'N-4-50', 'n-4-50', 'Single-Family', 'This zone addresses areas composed primarily of single-family homes on lots of at least 50 feet in width.', NULL, NULL, NULL, 60, NULL, NULL, NULL, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'n-4-50' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Civic Building', 'Detached House', 'Group Home', 'Day Care Home', 'Public Safety Facility', 'Bed & Breakfast (Special Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'D-C', 'd-c', 'Flex Commercial', 'This zone addresses general commercial and mixed-use areas that benefit from flexible form standards and are separate from, but within close proximity to, residential neighborhoods.', 4, NULL, 5000, 90, 0, 0, 0, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd-c' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('General Commercial', 'Mixed-Use', 'Professional or administrative offices', 'Retail and services') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'D-IL', 'd-il', 'Light Industrial', 'This zone addresses sites for low-impact and moderate-impact employment uses, benefiting from proximity to, but clear separation from, mixed-use residential neighborhoods, typically near highway, rail, and water access points.', 4, NULL, 5000, 100, 0, 0, 0, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd-il' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Low-impact employment uses', 'Moderate-impact employment uses', 'Industrial, artisan, light', 'Recycling facility', 'Research/laboratory facility', 'Storage yard', 'Warehouse/distribution', 'Freight terminal', 'Railway facilities', 'Truck stop', 'District energy system', 'Solar farm', 'Utilities and services, major and minor', 'Wind farm', 'Storage units (accessed individually from outside)', 'Self-storage facility (outdoor storage pods)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'D-IH', 'd-ih', 'Heavy Industrial', 'This zone addresses intensive, high-impact employment uses, generally incompatible with mixed-use residential neighborhoods, and typically benefits from isolated locations, often adjacent to highway, rail, and water access points.', 4, NULL, 5000, 100, 0, 0, 0, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd-ih' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Intensive, high-impact employment uses', 'Industrial, artisan, heavy', 'Recycling facility', 'Research/laboratory facility', 'Storage yard', 'Warehouse/distribution', 'Freight terminal', 'Railway facilities', 'Truck stop', 'District energy system', 'Solar farm', 'Utilities and services, major and minor', 'Wind farm', 'Storage units (accessed individually from outside)', 'Self-storage facility (outdoor storage pods)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'buffalo'), 'D-OG', 'd-og', 'Green', 'This zone addresses civic greens and parks, characterized primarily by trees and landscape, framed by landscape elements or building facades, and designed for passive or recreational use.', 3, NULL, 5000, 15, 15, 15, 15, 'No minimum off-street parking requirements citywide. Bicycle parking and accessible parking requirements apply.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd-og' AND z.city_id = (SELECT id FROM cities WHERE slug = 'buffalo') AND pu.name IN ('Civic greens', 'Parks', 'Passive recreational use', 'Recreational use') ON CONFLICT DO NOTHING;
