-- Gemini-extracted: Yonkers, NY
-- Generated: 2026-04-07T23:14:03.076Z
-- Zones: 8
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('New York', 'new-york', 'NY') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'new-york'), 'Westchester County', 'westchester-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'westchester-county' AND state_id = (SELECT id FROM states WHERE slug = 'new-york')), 'Yonkers', 'yonkers', 40.9312, -73.8987, 211569) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Detached Single-Family Dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-Family Dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment House (Medium Density)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood Business', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment House', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industry', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesale Business', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Storage', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Institutional', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'S-50', 's-50', 'Detached Single-Family Dwellings on 50-Foot Lots', 'This district is primarily for detached single-family residences on lots with a minimum width of 50 feet, aiming to maintain a low-density residential character.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Off-street parking spaces shall be provided on the lot. Refer to Table 43-4: Schedule of Parking Requirements for specific numbers.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 's-50' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Detached Single-Family Dwelling') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'T', 't', 'Two-Family Dwellings on 50-Foot Lots', 'This district is primarily for two-family residences on lots with a minimum width of 50 feet, allowing for a slightly higher residential density than single-family districts.', 35, NULL, 5000, NULL, NULL, NULL, NULL, 'Off-street parking spaces shall be provided on the lot. Refer to Table 43-4: Schedule of Parking Requirements for specific numbers.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 't' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Two-Family Dwelling') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'M', 'm', 'Apartment Houses, Medium-Density', 'This district is designated for medium-density apartment houses, accommodating multi-family residential developments.', 65, NULL, 5000, NULL, NULL, NULL, NULL, 'One parking space per apartment. Refer to Table 43-4: Schedule of Parking Requirements for specific numbers.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Apartment House (Medium Density)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'B', 'b', 'Neighborhood Business and Apartment Houses, Medium-Density', 'This district allows for neighborhood business uses along with medium-density apartment houses, fostering mixed-use environments at a local scale.', 35, NULL, 5000, NULL, NULL, NULL, NULL, 'Refer to Table 43-4: Schedule of Parking Requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Neighborhood Business', 'Apartment House (Medium Density)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'CB', 'cb', 'Central Business', 'This district is for central business activities, often with higher density and mixed-use potential, serving as a commercial hub for the city.', 50, 6, 0, NULL, NULL, NULL, NULL, 'For apartments: 1 per dwelling unit; Offices: 1 per 500 sq ft GFA; Restaurants: 1 per 150 sq ft GFA; Retail craft uses: 1 per 450 sq ft GFA; Planned shopping centers: 1 per 350 sq ft GFA. Refer to Table 43-4 for other uses. For parcels 10+ acres, no required rear yard and 100% maximum building coverage.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cb' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Business', 'Office', 'Retail', 'Apartment House') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'I', 'i', 'Industry', 'This district is designated for industrial uses, with residences generally excluded, supporting manufacturing, warehousing, and related activities.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to Table 43-4: Schedule of Parking Requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'i' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Industry', 'Wholesale Business', 'Storage') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'D-MX', 'd-mx', 'Mixed-Use District', 'This district features a high concentration of commercial, residential, and institutional developments in the downtown area, encouraging ground-floor commercial uses to activate the street-level environment.', 66, NULL, NULL, NULL, 0, 'Nonresidential: 0, Residential: 10', 0, 'New construction calculates parking from Table 43-4 and may subtract 10 spaces. Reduced parking for apartments on certain tracts: 1 space per apartment. Existing structures are exempt from new parking requirements if gross square footage or use doesn''t increase.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd-mx' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Commercial', 'Residential', 'Institutional') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'yonkers'), 'L-MX', 'l-mx', 'Ludlow Mixed-Use District', 'This district combines industrial, commercial, and residential uses, centered around the Ludlow Metro-North train station, supporting existing light industrial uses while encouraging mixed-use and residential buildings to create a vibrant, transit-oriented district.', 65, NULL, NULL, NULL, NULL, NULL, NULL, 'Required parking for uses is taken from Table 43-4. Accessory off-street parking lots are prohibited in front or side front setbacks.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'l-mx' AND z.city_id = (SELECT id FROM cities WHERE slug = 'yonkers') AND pu.name IN ('Industrial', 'Commercial', 'Residential') ON CONFLICT DO NOTHING;
