-- Gemini-extracted: New York City, NY
-- Generated: 2026-04-07T23:10:32.860Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('New York', 'new-york', 'NY') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'new-york'), 'New York County', 'new-york-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'new-york-county' AND state_id = (SELECT id FROM states WHERE slug = 'new-york')), 'New York City', 'new-york-city', 40.7128, -74.006, 8336817) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached residences', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Detached single-family residences', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Detached, semi-detached, and attached one- and two-family houses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small apartment buildings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family residential buildings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('High-rise residential buildings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Grocery stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Beauty parlors', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Drug stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small dry cleaners', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Local clothing stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Larger stores with more goods and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Corporate headquarters', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Large hotels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Department stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Entertainment facilities', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automobile showrooms and repair shops', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Gas stations', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Car washes', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('All commercial uses (except large, open amusements)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Certain community facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light industrial uses (woodworking shops, repair shops, wholesale service and storage facilities)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Most retail uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Houses of worship', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hospitals (by special permit)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential (limited to specific sub-districts or special permits)', 'Residential') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'R1', 'r1', 'Residence District (Low Density)', 'Leafy, low-density neighborhoods of large, single-family detached homes. These districts have sizeable required lot areas to produce large, roomy houses.', 'Not fixed, governed by sky exposure plane (R1-2A: max 35 ft building height).', 0.5, 9500, NULL, 20, 30, 15, 'One off-street parking space required for each dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Single-family detached residences', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'R2', 'r2', 'Residence District (Low Density)', 'These low-density districts allow for detached single-family residences, with slightly higher density permitted than R1 districts due to smaller lot requirements.', 'Not fixed, governed by a sky exposure plane.', 0.5, NULL, NULL, NULL, NULL, NULL, 'One off-street parking space is required for each dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Detached single-family residences', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'R4', 'r4', 'Residence District (Lower Density)', 'These lower-density districts allow for a variety of housing types, including single-family homes, duplexes, and small apartment buildings. Contextual regulations often aim to maintain neighborhood scale and character.', 'Contextual R4A: max 35 ft building height.', 1.35, NULL, 55, 'As deep as a neighboring yard (R4A).', NULL, NULL, 'More relaxed parking requirements for infill housing, typically two spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Detached, semi-detached, and attached one- and two-family houses', 'Small apartment buildings', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'R6', 'r6', 'Residence District (Medium Density)', 'R6 districts are medium-density residential areas found in built-up areas across boroughs, accommodating diverse building types from row houses to large-scale apartment developments. Developers can choose between standard height factor regulations or optional Quality Housing programs.', 'Not fixed for non-contextual (sky exposure plane). Quality Housing (wide streets): max 70 ft (75 ft with qualifying ground floor); (narrow streets): max 55 ft.', 0.78, NULL, NULL, 'Quality Housing (R6A equivalent): street wall no closer than adjacent street wall, but not farther than 10 feet.', NULL, NULL, 'Required for 70% of dwelling units, waived if five or fewer spaces are required.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Multi-family residential buildings', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'R10', 'r10', 'Residence District (Highest Density)', 'These districts permit the highest residential density in New York City, often resulting in high-rise apartment buildings. Development is typically governed by Quality Housing regulations or tower rules, with potential for increased density through affordable housing programs.', 'Tower-on-a-base: contextual base 60-85 ft, tower height controlled by FAR distribution. Quality Housing (wide streets): max 210 ft; (narrow streets): max 185 ft.', 10, NULL, 100, 'Tower portion: at least 10 feet from a wide street, 15 feet from a narrow street.', NULL, NULL, 'Not generally required in Manhattan Core, Long Island City, and parts of Downtown Brooklyn. Otherwise, 40% of dwelling units.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r10' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('High-rise residential buildings', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'C1', 'c1', 'Local Retail and Local Service Commercial District', 'C1 districts are commercial overlays mapped within residential areas, providing local retail and services for immediate neighborhood needs. Commercial uses are typically limited to the ground floor, with residential bulk governed by the underlying residential district.', 'Varies by underlying residential district and C1 sub-district (e.g., C1-3 in R8, R9, R10, R11 & R2: 85 ft max or 6 stories).', 1, NULL, NULL, NULL, NULL, NULL, 'Varies; lower numerical suffix generally requires more parking (e.g., C1-1 requires parking, C1-5 requires none).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Grocery stores', 'Restaurants', 'Beauty parlors', 'Drug stores', 'Small dry cleaners', 'Local clothing stores', 'Community facilities', 'Residential') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'C4', 'c4', 'Regional Retail Commercial District', 'C4 districts are regional retail centers with larger stores and a wider range of goods and services, often found along major thoroughfares. They permit residential development at densities equivalent to higher-density residential districts.', 'Varies by sub-district; C4-6, C4-7, C5 and C6-4 through C6-9 permit residential development at R10 density, where a tower is not required to have a contextual base.', 1, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Larger stores with more goods and services', 'Residential', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'C6', 'c6', 'General Central Commercial District', 'C6 districts are central business districts permitting a wide range of high-bulk commercial uses, including corporate headquarters, large hotels, and department stores. These districts often allow for high-rise mixed-use buildings with residential components.', 'Varies greatly by sub-district and contextual regulations; some allow towers to penetrate sky exposure plane.', 6, NULL, NULL, NULL, NULL, NULL, 'Generally not required, except in C6-3D.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Corporate headquarters', 'Large hotels', 'Department stores', 'Entertainment facilities', 'Residential', 'Community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'C8', 'c8', 'Heavy Commercial District', 'C8 districts bridge commercial and manufacturing uses, designed for heavy commercial and automotive services requiring large land areas. Residential uses are generally prohibited as-of-right in these districts.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 'Varies with district and use; C8-1 to C8-3 require substantial parking for automotive uses, C8-4 is usually exempt.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c8' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Automobile showrooms and repair shops', 'Warehouses', 'Gas stations', 'Car washes', 'All commercial uses (except large, open amusements)', 'Certain community facilities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'new-york-city'), 'M1', 'm1', 'Light Manufacturing District', 'M1 districts are light manufacturing zones, often serving as buffers between heavier industrial areas and residential or commercial districts. They permit light industrial uses, offices, hotels, most retail, and certain community facilities.', 'Controlled by sky exposure planes (e.g., M1-1: 30 ft above street line; M1-4: 60 ft above street line).', 1, NULL, NULL, NULL, 20, NULL, 'M1-1, M1-2, M1-3 districts require parking based on use and size; not required in Long Island City or M1-4, M1-5, M1-6 districts.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'new-york-city') AND pu.name IN ('Light industrial uses (woodworking shops, repair shops, wholesale service and storage facilities)', 'Offices', 'Hotels', 'Most retail uses', 'Houses of worship', 'Hospitals (by special permit)', 'Residential (limited to specific sub-districts or special permits)') ON CONFLICT DO NOTHING;
