-- Gemini-extracted: Rochester, NY
-- Generated: 2026-04-07T23:13:14.890Z
-- Zones: 9
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('New York', 'new-york', 'NY') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'new-york'), 'Monroe County', 'monroe-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'monroe-county' AND state_id = (SELECT id FROM states WHERE slug = 'new-york')), 'Rochester', 'rochester', 43.1566, -77.6088, 211328) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Family and group family day-care homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Adult family day-care homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Places of worship', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Convents and rectories', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home occupations', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office (in existing nonresidential structure, 6:00 a.m. - 9:00 p.m.)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live-work space', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Attached single-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling units (as part of mixed-use development)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bed-and-breakfast establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Family and group family day-care homes', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Adult family day-care homes', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day-care centers', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Convents and rectories', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public and semipublic uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sales and service (6:00 a.m. - 11:00 p.m.)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices (6:00 a.m. - 11:00 p.m.)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Funeral homes and mortuaries', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sales and service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed uses (not including industrial)', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public entertainment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Limited entertainment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling units (second story or above, as part of mixed-use development)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed uses', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hospitals', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Animal hospitals and kennels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Animal day care', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research laboratories including testing facilities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Corporate headquarters, regional headquarters and their administrative offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Local service offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing, high-tech or light industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouses and wholesale distribution facilities', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use facilities', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Vehicle repair stations', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Vehicle and equipment rental, sales and storage', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Recycling centers', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Technical and vocational schools', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dwelling unit conversions', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bars, restaurants and banquet facilities', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Funeral parlors and mortuaries', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Pawnbrokers', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Secondhand dealers', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential development', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Institutional uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cultural uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Entertainment uses and activities', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Festivals, events and activities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Publicly owned parks, squares, recreational areas, natural wildlife areas and other open areas', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cemeteries, including associated facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Botanical gardens, arboretums and conservatories', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public marinas, boat launches, boat docks and fishing docks', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Outdoor recreational facilities (hiking/bicycle trails, greens, commons, sitting/picnic areas)', 'Civic') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'R-1', 'r-1', 'Low-Density Residential District', 'The R-1 Low-Density Residential District is intended to maintain residential areas at relatively low densities, characterized predominantly by owner-occupied, single-family detached and attached homes, while preserving unobstructed front yards and pedestrian-scale streetscapes.', 35, NULL, '[object Object]', 50, 'Average of 2 adjoining lots or block frontage, or 20 feet (minimum); average of 2 adjoining lots or block frontage (maximum).', '20 feet or average rear yard setback on block, but no less than 10 feet.', '5 feet minimum, 15 feet combined for detached principal; 0 feet for attached principal (except 5 feet minimum when adjacent to detached structure, combined 15 feet).', 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Single-family detached dwellings', 'Single-family attached dwellings', 'Family and group family day-care homes', 'Adult family day-care homes', 'Places of worship', 'Convents and rectories', 'Home occupations', 'Office (in existing nonresidential structure, 6:00 a.m. - 9:00 p.m.)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'R-2', 'r-2', 'Medium-Density Residential District', 'The R-2 Medium-Density Residential District provides a mix of housing choices, including single-family, two-family, and multifamily residential, with bulk and density regulations that maintain a lower-density scale, located proximate to neighborhood-scale shopping and service opportunities.', 35, NULL, '[object Object]', 50, 'Average of 2 adjoining lots or block frontage, or 20 feet.', '10 feet.', '5 feet minimum, 15 feet combined for detached principal; 10 feet minimum, 25 feet combined for principal use or structure.', 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Single-family detached dwellings', 'Single-family attached dwellings', 'Two-family dwellings', 'Family and group family day-care homes', 'Adult family day-care homes', 'Places of worship', 'Convents and rectories', 'Home occupations', 'Office (in existing nonresidential structure, 6:00 a.m. - 9:00 p.m.)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'R-3', 'r-3', 'High-Density Residential District', 'The R-3 High-Density Residential District protects, preserves, and enhances existing residential areas of higher density, including multifamily dwellings mixed with other housing types, and accommodates higher-density housing while maintaining and enhancing existing residential areas.', 'Two times the width of the lot frontage for principal uses; 15 feet for detached accessory uses.', NULL, '[object Object]', 50, 'Average of block or 20 feet (whichever is more), but no more than 5 feet larger than average of 2 adjoining lots.', '1/3 the building height or 20 feet, whichever is greater.', '5 feet minimum, 15 feet combined for detached principal; 1/3 building height or 10 feet (whichever is greater) for multifamily principal.', 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Single-family detached dwellings', 'Single-family attached dwellings', 'Two-family dwellings', 'Multifamily dwellings', 'Live-work space', 'Family and group family day-care homes', 'Adult family day-care homes', 'Places of worship', 'Convents and rectories', 'Home occupations', 'Office (in existing nonresidential structure, 6:00 a.m. - 9:00 p.m.)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'C-1', 'c-1', 'Neighborhood Center District', 'The C-1 Neighborhood Center District provides for small-scale commercial uses offering primarily convenience shopping and services for adjacent residential areas, with low intensity and unobtrusive operations compatible with the surrounding neighborhood.', NULL, NULL, NULL, NULL, '0-5 feet or average of corridor/district, no more than 5 feet larger/smaller than average of 2 adjoining lots.', '0 feet unless adjacent to a residential district, then same as adjacent residential district.', '0 feet unless adjacent to a residential district, then same as adjacent residential district.', 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Attached single-family dwellings', 'Dwelling units (as part of mixed-use development)', 'Live-work space', 'Bed-and-breakfast establishments', 'Family and group family day-care homes', 'Adult family day-care homes', 'Day-care centers', 'Places of worship', 'Convents and rectories', 'Public and semipublic uses', 'Retail sales and service (6:00 a.m. - 11:00 p.m.)', 'Offices (6:00 a.m. - 11:00 p.m.)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'C-2', 'c-2', 'Community Center District', 'The C-2 Community Center District provides diverse commercial development along gateway transportation corridors and neighborhood or village centers with a dense mixture of uses such as housing, retail, and other complementary uses that serve the adjacent neighborhood and the community at large.', NULL, NULL, '[object Object]', NULL, NULL, NULL, NULL, 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Single-family attached dwellings', 'Multifamily dwellings', 'Live-work space', 'Bed-and-breakfast establishments', 'Family and group family day-care homes', 'Adult family day-care homes', 'Day-care centers', 'Places of worship', 'Convents and rectories', 'Public and semipublic uses', 'Funeral homes and mortuaries', 'Retail sales and service', 'Mixed uses (not including industrial)', 'Public entertainment', 'Limited entertainment') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'C-3', 'c-3', 'Regional Destination Center District', 'The C-3 Regional Destination Center District provides locations for regional-scaled growth and development of commercial and light industrial uses, accessible to and serving a regional market, with site design and buffering to mitigate impacts on adjacent areas.', NULL, NULL, NULL, NULL, NULL, NULL, '0 feet unless adjacent to a residential district, then 30 feet. [cite: 23 in previous turn]', 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Dwelling units (second story or above, as part of mixed-use development)', 'Live-work space', 'Mixed uses', 'Day-care centers', 'Places of worship', 'Public and semipublic uses', 'Hospitals', 'Animal hospitals and kennels', 'Animal day care', 'Funeral homes and mortuaries', 'Retail sales and service') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'M-1', 'm-1', 'Industrial District', 'The M-1 Industrial District promotes the retention and growth of employment opportunities by providing areas where a broad range of industrial uses may locate and where options for complementary uses exist in older two-story and multistory buildings.', NULL, NULL, NULL, NULL, 'N/A unless adjacent to a residential district, then same as required front yard setback in residential district.', 'N/A unless adjacent to a residential district, then same as required rear yard setback in residential district.', 'N/A unless adjacent to a residential district, then same as required side yard setback in residential district.', 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code; special permit uses may have parking requirements waived or modified.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Research laboratories including testing facilities', 'Corporate headquarters, regional headquarters and their administrative offices', 'Local service offices', 'Manufacturing, high-tech or light industrial uses', 'Warehouses and wholesale distribution facilities', 'Mixed-use facilities', 'Vehicle repair stations', 'Vehicle and equipment rental, sales and storage', 'Recycling centers', 'Technical and vocational schools', 'Dwelling unit conversions', 'Live-work space', 'Retail sales and service', 'Bars, restaurants and banquet facilities', 'Public entertainment', 'Public and semipublic uses', 'Day-care centers', 'Funeral parlors and mortuaries', 'Places of worship', 'Pawnbrokers', 'Secondhand dealers') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'CCD', 'ccd', 'Center City District (Base District)', 'The CCD is intended to foster a vibrant, safe, twenty-four-hour Center City by encouraging residential development while retaining and further developing a broad range of commercial, office, institutional, public, cultural and entertainment uses and activities. [cite: 13 in previous turn]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Exempt from minimum off-street parking requirements (§ 120-65). [cite: 13 in previous turn]') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ccd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Residential development', 'Commercial uses', 'Office uses', 'Institutional uses', 'Public uses', 'Cultural uses', 'Entertainment uses and activities', 'Festivals, events and activities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'rochester'), 'O-S', 'o-s', 'Open Space District', 'The O-S Open Space District preserves and enhances Rochester''s open spaces and recreational areas by protecting these natural amenities and restricting development that does not respect these environmentally sensitive areas. It applies to publicly owned parks, squares, recreational areas, natural wildlife areas, the waterfront, and cemeteries.', 25, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to general off-street parking requirements in § 120-173 of the Zoning Code.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'o-s' AND z.city_id = (SELECT id FROM cities WHERE slug = 'rochester') AND pu.name IN ('Publicly owned parks, squares, recreational areas, natural wildlife areas and other open areas', 'Cemeteries, including associated facilities', 'Botanical gardens, arboretums and conservatories', 'Public marinas, boat launches, boat docks and fishing docks', 'Outdoor recreational facilities (hiking/bicycle trails, greens, commons, sitting/picnic areas)') ON CONFLICT DO NOTHING;
