-- Gemini-extracted: Fort Worth, TX
-- Generated: 2026-04-07T22:06:46.838Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Tarrant County', 'tarrant-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Fort Worth', 'fort-worth', 32.7555, -97.3308, 958692) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('One-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Schools', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('One-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily dwelling units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplexes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manor Houses (2+ units)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartments/Condominiums', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Amusement (nightclubs, pool halls, taverns, skating rinks)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Used furniture stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Alcohol sales and on-premises consumption', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mini-warehouses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('All uses permitted in ''F''', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Other retail uses not considered offensive or noxious', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('All uses permitted in ''G''', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Food processing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Animal hospitals and outdoor kennels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Transportation terminals', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Batch plant (temporary)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Outside sales/storage', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Printing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('All uses permitted in ''I''', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Breweries', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cement products', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Power plants', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Grain elevators', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Poultry slaughtering', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Variety of housing types', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood-serving commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Institutional uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential, commercial, and institutional uses may occupy the same building lot', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('College or university', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day care center (child or adult)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('School, elementary or secondary (public or private)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business college or commercial school', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Government office facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Museum, library or fine art center', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family detached', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex/two-family attached dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('One-family attached (townhouse, rowhouse)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily dwelling apartment', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily dwelling (up to 8 units)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily dwelling (9+ units)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('One dwelling unit when part of a business or civic use; security residence', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Group home I', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Group home II', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Select light industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail and restaurant uses on the ground floor', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Microbrewery', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Microdistillery', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Brewpub', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bars larger than 2,000 sq ft (Conditional Use Permit required)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'A-5', 'a-5', 'One-Family', 'This district is intended for one-family detached dwellings with a minimum lot size of 5,000 square feet, along with compatible civic uses.', NULL, NULL, 5000, NULL, 20, 25, NULL, 'Fort Worth''s baseline table still governs (e.g., 1–4 spaces per dwelling in some residential districts, plus multifamily formulas). Parking spaces must be hard-surfaced and dust free.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'a-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('One-family detached dwellings', 'Churches', 'Schools', 'Parks') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'B', 'b', 'Two-Family', 'This district allows for one-family and two-family detached and attached dwellings, with varying minimum lot sizes based on dwelling type.', NULL, NULL, 5000, NULL, 20, 25, NULL, 'Fort Worth''s baseline table still governs (e.g., 1–4 spaces per dwelling in some residential districts, plus multifamily formulas). Parking spaces must be hard-surfaced and dust free.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('One-family detached dwellings', 'Two-family detached dwellings', 'One-family attached dwellings', 'Two-family attached dwellings', 'Churches', 'Schools', 'Parks') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'C', 'c', 'Medium Density Multifamily', 'This district is designated for multifamily dwelling units with a maximum density of 18 dwelling units per acre.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Fort Worth''s baseline table still governs (e.g., 1–4 spaces per dwelling in some residential districts, plus multifamily formulas). A multi-family development permit (MFD) is required.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('Multifamily dwelling units') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'UR', 'ur', 'Urban Residential', 'This district provides a higher density, residential-only, pedestrian-oriented development, serving as a transition zone between low-density single-family neighborhoods and higher-density commercial areas.', 42, NULL, NULL, NULL, 20, 20, NULL, 'Single Family Detached: 2 spaces per dwelling unit. Townhouse: 1-2 spaces per dwelling unit. Duplex & Manor House (2+ units): 1-2 spaces per dwelling unit plus 1 space per bedroom over three. Apartments/Condominiums: 0.5-1 space per bedroom plus 2 spaces per 500 sq ft of leasing/social rooms. On-street parking may not count toward required parking.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ur' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('Single-family detached dwellings', 'Townhouses', 'Duplexes', 'Manor Houses (2+ units)', 'Apartments/Condominiums') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'F', 'f', 'General Commercial', 'This district permits general commercial uses, including amusement establishments, and allows for alcohol sales and on-premises consumption.', 45, NULL, NULL, NULL, NULL, NULL, NULL, 'Most retail stores require 1 space per 200 square feet of gross floor area. Supplemental standards apply when adjacent to residential districts.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'f' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('Amusement (nightclubs, pool halls, taverns, skating rinks)', 'Used furniture stores', 'Alcohol sales and on-premises consumption', 'Mini-warehouses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'G', 'g', 'Intensive Commercial', 'This district allows for intensive commercial uses, including all uses permitted in ''F'', plus other retail uses not considered offensive or noxious, with less restrictive area regulations.', 120, NULL, NULL, NULL, NULL, NULL, NULL, 'Most retail stores require 1 space per 200 square feet of gross floor area. Supplemental standards apply when adjacent to residential districts.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'g' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('All uses permitted in ''F''', 'Other retail uses not considered offensive or noxious', 'Alcohol sales and on-premises consumption', 'Mini-warehouses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'I', 'i', 'Light Industrial', 'This district permits light industrial uses, including all uses allowed in ''G'', along with food processing, warehousing, and light manufacturing.', 55, NULL, NULL, NULL, NULL, NULL, NULL, 'Parking requirements are based on the use and size of the establishment. Hard surface parking is not required for non-passenger vehicles and tractor trailers for industrial uses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'i' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('All uses permitted in ''G''', 'Food processing', 'Animal hospitals and outdoor kennels', 'Transportation terminals', 'Batch plant (temporary)', 'Warehousing', 'Outside sales/storage', 'Printing', 'Light manufacturing', 'Alcohol sales and on-premises consumption', 'Mini-warehouses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'J', 'j', 'Medium Industrial', 'This district allows for medium industrial uses, including all uses permitted in ''I'', plus breweries, cement products, and power plants.', 120, NULL, NULL, NULL, NULL, NULL, NULL, 'Parking requirements are based on the use and size of the establishment. Hard surface parking is not required for non-passenger vehicles and tractor trailers for industrial uses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'j' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('All uses permitted in ''I''', 'Breweries', 'Cement products', 'Power plants', 'Grain elevators', 'Poultry slaughtering', 'Light manufacturing', 'Alcohol sales and on-premises consumption') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'MU-1', 'mu-1', 'Low Intensity Mixed-Use', 'This district encourages higher density, mixed-use, pedestrian-oriented development, concentrating a variety of housing types among neighborhood-serving commercial and institutional uses.', 60, NULL, NULL, NULL, 20, NULL, NULL, 'Parking requirements are for commercial and mixed-use parking, and residential parking. For mixed-use or multifamily in commercial zones, the city can''t require more than one space per dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mu-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('Variety of housing types', 'Neighborhood-serving commercial uses', 'Institutional uses', 'Residential, commercial, and institutional uses may occupy the same building lot', 'College or university', 'Day care center (child or adult)', 'School, elementary or secondary (public or private)', 'Business college or commercial school', 'Government office facility', 'Museum, library or fine art center', 'Two-family detached', 'Duplex/two-family attached dwelling', 'One-family attached (townhouse, rowhouse)', 'Multifamily dwelling apartment', 'Multifamily dwelling (up to 8 units)', 'Multifamily dwelling (9+ units)', 'One dwelling unit when part of a business or civic use; security residence', 'Community home', 'Group home I', 'Group home II') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'fort-worth'), 'MU-2', 'mu-2', 'High Intensity Mixed-Use', 'This district promotes higher density, mixed-use, pedestrian-oriented development, concentrating a variety of housing types among commercial, institutional, and select light industrial uses.', 120, NULL, NULL, NULL, 20, 5, 20, 'Parking requirements are for commercial and mixed-use parking, and residential parking. For mixed-use or multifamily in commercial zones, the city can''t require more than one space per dwelling unit.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mu-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth') AND pu.name IN ('Variety of housing types', 'Commercial uses', 'Institutional uses', 'Select light industrial uses', 'Retail and restaurant uses on the ground floor', 'Microbrewery', 'Microdistillery', 'Brewpub', 'Bars larger than 2,000 sq ft (Conditional Use Permit required)', 'College or university', 'Day care center (child or adult)', 'School, elementary or secondary (public or private)', 'Business college or commercial school', 'Government office facility', 'Museum, library or fine art center', 'Two-family detached', 'Duplex/two-family attached dwelling', 'One-family attached (townhouse, rowhouse)', 'Multifamily dwelling apartment', 'Multifamily dwelling (up to 8 units)', 'Multifamily dwelling (9+ units)', 'One dwelling unit when part of a business or civic use; security residence', 'Community home', 'Group home I', 'Group home II') ON CONFLICT DO NOTHING;
