-- Gemini-extracted: Plano, TX
-- Generated: 2026-04-07T22:55:55.742Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Collin County', 'collin-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'collin-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Plano', 'plano', 33.0198, -96.6989, 285494) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Accessory Building or Use', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Caretaker''s/Guard''s Residence', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Construction Yard (Temporary)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Field Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home-Based Business (No-Impact)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home Occupation', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Backyard Cottage', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Electrical Substation', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private Utility (other than listed)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service Yard (Public or Utility)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Sewage Treatment Plant', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Transportation and Utility Structures/Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Utility Distribution/Transmission Line', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Water Treatment Plant', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Farm, Ranch, Garden, or Orchard', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Fire Station/Public Safety Building', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Park/Playground', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Religious Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('School (Public or Parochial)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('School (Private)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Patio Homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Independent Living Facility', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live-In Management STR', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Assisted Living Facility', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day Care Center', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial Drone Delivery Hub (Small)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Golf Course/Country Club', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Helistop', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hospital', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Long-term Care Facility', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office (Professional/General Administrative)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Post Office (Government and Private)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private Recreation Facility', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Rehabilitation Care Institution', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research and Development Center', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Short-Term Rental (STR)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily Residence', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Convenience Store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Furniture, Home Furnishings, and Equipment Store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Garden Center', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing, assembling or packaging of products from previously prepared materials', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial Drone Delivery Hub (Small)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Tattooing and permanent cosmetics, or body piercing', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail (small grocers, farmers markets, boutiques)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Entertainment (neighborhood theaters, dance studios)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional and Medical Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Services (salons, banks, gyms)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses (developed according to RCD standards)', 'Residential') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'SF-6', 'sf-6', 'Single Family Residence-6', 'This district is for single-family detached residential development with a minimum lot size of 6,000 square feet.', NULL, NULL, 6000, 60, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'sf-6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Accessory Building or Use', 'Caretaker''s/Guard''s Residence', 'Construction Yard (Temporary)', 'Field Office', 'Home-Based Business (No-Impact)', 'Home Occupation', 'Backyard Cottage', 'Electrical Substation', 'Private Utility (other than listed)', 'Service Yard (Public or Utility)', 'Sewage Treatment Plant', 'Transportation and Utility Structures/Facility', 'Utility Distribution/Transmission Line', 'Water Treatment Plant') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'SF-7', 'sf-7', 'Single Family Residence-7', 'This district is for single-family detached residential development with a minimum lot size of 7,000 square feet.', NULL, NULL, 7000, 60, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'sf-7' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Accessory Building or Use', 'Caretaker''s/Guard''s Residence', 'Construction Yard (Temporary)', 'Field Office', 'Home-Based Business (No-Impact)', 'Home Occupation', 'Backyard Cottage', 'Farm, Ranch, Garden, or Orchard', 'Fire Station/Public Safety Building', 'Park/Playground', 'Religious Facility', 'School (Public or Parochial)', 'School (Private)', 'Electrical Substation', 'Private Utility (other than listed)', 'Service Yard (Public or Utility)', 'Sewage Treatment Plant', 'Transportation and Utility Structures/Facility', 'Utility Distribution/Transmission Line', 'Water Treatment Plant') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'SF-9', 'sf-9', 'Single Family Residence-9', 'This district is for single-family detached residential development with a minimum lot size of 9,000 square feet.', NULL, NULL, 9000, 60, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), '2F', '2f', 'Two Family Residence Duplex', 'The 2F district is designed to provide for areas of two-family development that are consistent in design and in development patterns with typical single-family detached development. The 2F district is intended to encourage single-family ownership by permitting the division of a 2F lot along the common wall of the 2 residential units of a duplex.', NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'PH', 'ph', 'Patio Home', 'The PH district is intended to provide for areas of detached, single-family development in a clustered lot pattern with a common usable open space system that is an integral part of the development.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ph' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Patio Homes') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'MF-1', 'mf-1', 'Multifamily Residence-1', 'This district is for multifamily residential developments.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Parking reductions may be granted for multifamily properties when the area used by reduced parking is exchanged for additional usable open space.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mf-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Independent Living Facility', 'Live-In Management STR', 'Assisted Living Facility', 'Day Care Center', 'Electrical Substation', 'Transportation and Utility Structures/Facility') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'CC', 'cc', 'Corridor Commercial', 'This district is intended for commercial uses along major corridors, with standards designed for compatibility with surrounding residential neighborhoods.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'CE', 'ce', 'Commercial Employment', 'The CE district is intended to provide flexibility for integrated developments that may include retail, office, commercial, and light manufacturing, with a major focus on corporate headquarters and research facilities in a campus-like setting.', NULL, NULL, NULL, NULL, 50, 10, NULL, 'Loading spaces are required as per Sec. 16.1400 for retail, commercial, and industrial uses. Parking is not required for an accessory commercial drone delivery hub use.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ce' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Commercial Drone Delivery Hub (Small)', 'Golf Course/Country Club', 'Helistop', 'Hospital', 'Long-term Care Facility', 'Medical Office', 'Office (Professional/General Administrative)', 'Park/Playground', 'Post Office (Government and Private)', 'Private Recreation Facility', 'Rehabilitation Care Institution', 'Religious Facility', 'Research and Development Center', 'School (Private)', 'School (Public or Parochial)', 'Short-Term Rental (STR)', 'Multifamily Residence', 'Independent Living Facility', 'Convenience Store', 'Furniture, Home Furnishings, and Equipment Store', 'Garden Center') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'LI-1', 'li-1', 'Light Industrial-1', 'The LI Light Industrial District is designed to accommodate light manufacturing, assembly, research and wholesale activities with limitations on outdoor storage. Uses are generally within a completely enclosed building or structure.', 20, NULL, 20000, 85, 30, NULL, NULL, 'Loading spaces shall be provided as per Sec. 16.1400 for retail, commercial, and industrial uses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'li-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Manufacturing, assembling or packaging of products from previously prepared materials', 'Commercial Drone Delivery Hub (Small)', 'Tattooing and permanent cosmetics, or body piercing') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'plano'), 'NBD', 'nbd', 'Neighborhood Business Design District', 'The NBD district is intended to create a zoning district that caters to a pleasant and active pedestrian-oriented environment defined by traditional neighborhood-friendly commercial and residential uses, low-rise building heights and masses, walkable streets defined by storefronts and building faces, and required open space.', 50, NULL, 435600, NULL, NULL, NULL, NULL, 'On-street parking along major and minor streets provides an additional buffer for pedestrians. Parking garages must be set back a minimum of 150 feet from existing residential zoning districts or residential uses outside of the NBD district.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nbd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano') AND pu.name IN ('Retail (small grocers, farmers markets, boutiques)', 'Entertainment (neighborhood theaters, dance studios)', 'Professional and Medical Offices', 'Services (salons, banks, gyms)', 'Residential uses (developed according to RCD standards)') ON CONFLICT DO NOTHING;
