-- Gemini-extracted: El Paso, TX
-- Generated: 2026-04-07T22:52:54.643Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'El Paso County', 'el-paso-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'el-paso-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'El Paso', 'el-paso', 31.7619, -106.485, 681124) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Duplex and single-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple-family dwellings and dwelling groups', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Boardinghouses and rooming houses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public schools, parochial schools, kindergartens', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public parks and recreational facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches and similar religious institutions', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('High-density residential development', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Compatible business and professional office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Neighborhood convenience goods and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business and professional offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail category uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Establishments providing goods or rendering services supporting community trade', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Personal service shops', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sales and/or service type uses selling new merchandise only', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bakeries designed for retail sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bicycle sales and repair shops', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dancing schools, martial arts, music schools, yoga', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day nurseries', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Dog and cat hospitals or small animal hospitals (with conditions)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy commercial uses characterized by automotive and light warehousing', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Major locations of commerce, service and employment activities', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light-intensity industries involving manufacturing, assembling, distribution and warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Supporting commercial uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Intensive industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing and industrial uses, which may include related outside storage of raw or finished materials', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Walk up retail, commercial and professional office land uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Semi-rural (very-low density) residential uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Agricultural uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'R-3', 'r-3', 'Residential Multiple-Family District', 'Intended to provide opportunities for attractive living environments at densities greater than permitted in other residential districts, encouraging high-density development of affordable single-family and multiple-family housing types.', 35, NULL, 6000, NULL, 20, NULL, NULL, 'Off-street parking required, details in Appendix C of Title 20.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Duplex and single-family attached dwellings', 'Multiple-family dwellings and dwelling groups', 'Boardinghouses and rooming houses', 'Public schools, parochial schools, kindergartens', 'Public parks and recreational facilities', 'Churches and similar religious institutions') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'A-1', 'a-1', 'Apartment District', 'Intended for medium densities of dwelling units, supported by higher intensity land uses at the periphery of single-family neighborhoods, preserving overall character and architectural integrity. Permits building types designed for transition from low-density residential to other residential areas, and certain non-residential uses and support facilities.', 45, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20. SB 840 limits parking to one space per dwelling unit or prohibits requiring a multilevel parking structure for mixed-use/multifamily residential projects.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'a-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Multifamily dwellings', 'Office uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'A-4', 'a-4', 'Planned Apartment District', 'Promotes and preserves a diversity of residential dwelling types at the highest densities within the city, integrating compatible business and professional office uses. Allows for concentrations of population through multi-story facilities.', 45, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20. SB 840 limits parking to one space per dwelling unit or prohibits requiring a multilevel parking structure for mixed-use/multifamily residential projects.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'a-4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('High-density residential development', 'Compatible business and professional office uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'C-1', 'c-1', 'Commercial District', 'Serves the needs of surrounding residential neighborhoods by providing compatible neighborhood convenience goods and services. Permits business and professional offices and retail uses within adjacent residential areas.', 45, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20. Some areas are eliminating parking minimums.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Neighborhood convenience goods and services', 'Business and professional offices', 'Retail category uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'C-2', 'c-2', 'Commercial District', 'Accommodates establishments providing goods or rendering services which are used in support of the community''s trade and service establishments and serving multi-neighborhoods within a planning area of the city.', 45, NULL, NULL, NULL, NULL, 10, NULL, 'Details in Appendix C of Title 20. Some areas are eliminating parking minimums.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Establishments providing goods or rendering services supporting community trade', 'Offices', 'Personal service shops', 'Retail sales and/or service type uses selling new merchandise only', 'Bakeries designed for retail sales', 'Bicycle sales and repair shops', 'Dancing schools, martial arts, music schools, yoga', 'Day nurseries', 'Dog and cat hospitals or small animal hospitals (with conditions)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'C-4', 'c-4', 'Commercial District', 'Intended to serve the entire City, permitting heavy commercial uses characterized by automotive and light warehousing. Provides a transition from general business areas to industrial uses and accommodates major locations of commerce, service, and employment activities.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20. Some areas are eliminating parking minimums.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Heavy commercial uses characterized by automotive and light warehousing', 'Major locations of commerce, service and employment activities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'M-1', 'm-1', 'Light Manufacturing District', 'Provides locations for light-intensity industries involving manufacturing, assembling, distribution, and warehousing, while supporting commercial uses and preserving a light industrial nature regarding noise, smoke, odors, dust, and vibrations.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Light-intensity industries involving manufacturing, assembling, distribution and warehousing', 'Supporting commercial uses') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'M-2', 'm-2', 'Heavy Manufacturing District', 'Provides for the most intensive of industrial uses which may be characteristic of nuisance or hazardous conditions. Regulations require reasonable standards for the protection and preservation of compatibility with adjacent areas.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Intensive industrial uses', 'Manufacturing and industrial uses, which may include related outside storage of raw or finished materials') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'GMU', 'gmu', 'General Mixed-Use District', 'Provides for large-scale developments that can function as individual neighborhoods, small-scale developments requiring flexibility due to unique design, or transitional areas between dissimilar land uses. Encourages walkability, public transportation, and pedestrian linkages.', 45, NULL, NULL, NULL, 0, 0, 0, 'Determined by Title 20 and Appendix C of the El Paso Municipal Code. On-street parking available along the corresponding frontage lines shall be counted toward the parking requirement. May also be provided within one-quarter mile of the site. SB 840 limits parking to one space per dwelling unit or prohibits requiring a multilevel parking structure for mixed-use/multifamily residential projects.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'gmu' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Walk up retail, commercial and professional office land uses', 'Residential', 'Office', 'Retail') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'el-paso'), 'R-F', 'r-f', 'Ranch and Farm District', 'Provides for primarily fallow or agricultural areas within the city, protecting and conserving these areas within and adjacent to urban development. Affords areas where semi-rural (very-low density) residential and agricultural uses can be maintained without impairment from higher density development.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Details in Appendix C of Title 20.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-f' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso') AND pu.name IN ('Semi-rural (very-low density) residential uses', 'Agricultural uses') ON CONFLICT DO NOTHING;
