-- Gemini-extracted: Arlington, TX
-- Generated: 2026-04-07T22:09:02.168Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Tarrant County', 'tarrant-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Arlington', 'arlington', 32.7357, -97.1081, 394266) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory development', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Religious assemblies', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Educational facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Government administration and civic buildings', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public parks', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('High-density multi-family residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Attached residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live/work units', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential units over ground-floor non-residential uses', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Lodge | fraternal organization (with Specific Use Permit)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Large-lot single-family detached residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Agricultural activities', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bank or Financial Institution', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Catering service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurant', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurant, take-out and delivery only', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Sidewalk cafe', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office, business or professional', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('General personal services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Alternative Financial Institution (Specific Use Permit)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day care center (Specific Use Permit)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automobile sales and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Car washes', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurant with drive-through (Specific Use Permit)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Drive-through and drive-in restaurants', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel, luxury', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel, upper upscale', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel, upscale (Specific Use Permit)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel, upper midscale (Restricted)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel, midscale (Restricted)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel, economy (Restricted)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light industrial', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Processing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Indoor light industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Supporting business and office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Auto service center (by right or Specific Use Permit depending on distance from right-of-way)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Auto repair garage, major (by right or Specific Use Permit depending on distance from right-of-way)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Trailer camp | RV park', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy industrial', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial facilities', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Institutional facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Recreational facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Service facilities (e.g., grocery and convenience stores, drug stores, religious assembly, personal household services)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use development or building', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Downtown, civic, service, office, institutional, cultural, residential, and other uses', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bar', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mixed-use development or building (Specific Use Permit)', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'RS-7.2', 'rs-7-2', 'Residential Single-Family 7.2', 'Intended to accommodate single-family detached residential uses and typical accessory development at low densities (minimum 7,200-square foot lots).', 36, NULL, 7200, 55, 25, 5, 5, '2 spaces per dwelling.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-7-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Single-family detached residential', 'Accessory development', 'Religious assemblies', 'Educational facilities', 'Government administration and civic buildings', 'Public parks') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'RMF-22', 'rmf-22', 'Residential Multi-Family 22', 'Established to provide opportunities for high-density multi-family residential uses with a maximum density of 22 units per acre, designed to be compatible with their sites and surroundings. The district also allows medium-density residential uses, including attached residential, live/work units, and residential units over ground-floor non-residential uses.', 40, NULL, NULL, NULL, NULL, 10, NULL, '1 space per bedroom.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rmf-22' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('High-density multi-family residential', 'Attached residential', 'Live/work units', 'Residential units over ground-floor non-residential uses', 'Lodge | fraternal organization (with Specific Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'RE', 're', 'Residential Estate', 'Intended to accommodate large-lot (minimum one acre) single-family detached residential uses, accessory development, and select agricultural activities.', NULL, NULL, 43560, NULL, 20, NULL, NULL, '2 spaces per dwelling.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 're' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Large-lot single-family detached residential', 'Accessory development', 'Agricultural activities') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'NC', 'nc', 'Neighborhood Commercial', 'Intended to provide sites for businesses serving the daily needs of nearby residential areas and for small-scale offices.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Bank or Financial Institution', 'Catering service', 'Restaurant', 'Restaurant, take-out and delivery only', 'Sidewalk cafe', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'GC', 'gc', 'General Commercial', 'Intended primarily to provide sites for a broad range of commercial uses including automobile sales and services, car washes, restaurants, offices, warehousing, and commercial services.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'gc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Automobile sales and services', 'Car washes', 'Restaurants', 'Offices', 'Warehousing', 'Commercial services', 'Bank or Financial Institution', 'Catering service', 'Restaurant, take-out and delivery only', 'Sidewalk cafe', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)', 'Restaurant with drive-through (Specific Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'HC', 'hc', 'Highway Commercial', 'Intended primarily to provide sites for commercial uses including automobile sales and services, hotels, drive-through and drive-in restaurants, offices, warehousing, and commercial services adjacent to regional roadways and highways.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'hc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Automobile sales and services', 'Hotels', 'Drive-through and drive-in restaurants', 'Offices', 'Warehousing', 'Commercial services', 'Bank or Financial Institution', 'Catering service', 'Restaurant', 'Restaurant, take-out and delivery only', 'Sidewalk cafe', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)', 'Restaurant with drive-through (Specific Use Permit)', 'Hotel, luxury', 'Hotel, upper upscale', 'Hotel, upscale (Specific Use Permit)', 'Hotel, upper midscale (Restricted)', 'Hotel, midscale (Restricted)', 'Hotel, economy (Restricted)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'LI', 'li', 'Light Industrial', 'Intended to provide for the development of research, light industrial, processing, warehousing and other indoor light industrial uses, as well as supporting business and office uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'li' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Research', 'Light industrial', 'Processing', 'Warehousing', 'Indoor light industrial uses', 'Supporting business and office uses', 'Auto service center (by right or Specific Use Permit depending on distance from right-of-way)', 'Auto repair garage, major (by right or Specific Use Permit depending on distance from right-of-way)', 'Trailer camp | RV park', 'Bank or Financial Institution', 'Catering service', 'Restaurant', 'Restaurant, take-out and delivery only', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'IM', 'im', 'Industrial Manufacturing', 'Intended to provide for the development of heavy industrial and manufacturing uses, as well as supporting business and office uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'im' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Heavy industrial', 'Manufacturing uses', 'Supporting business and office uses', 'Bank or Financial Institution', 'Catering service', 'Restaurant', 'Restaurant, take-out and delivery only', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'NMU', 'nmu', 'Neighborhood Mixed-Use', 'Intended to encourage the redevelopment of traditional suburban commercial centers as higher-density, mixed-use, urban-scale districts developed as nodal centers or linear-oriented commercial retail development.', NULL, NULL, NULL, NULL, 0, NULL, NULL, 'Total requirement is the sum of requirements for various uses, may be reduced with parking evaluation.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nmu' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Commercial facilities', 'Institutional facilities', 'Recreational facilities', 'Service facilities (e.g., grocery and convenience stores, drug stores, religious assembly, personal household services)', 'Multi-family residential', 'Office uses', 'Bank or Financial Institution', 'Catering service', 'Restaurant', 'Restaurant, take-out and delivery only', 'Sidewalk cafe', 'Mixed-use development or building', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)', 'Restaurant with drive-through (Specific Use Permit)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'arlington'), 'DB', 'db', 'Downtown Business', 'Provides concentrated downtown, civic, service, office, institutional, cultural, residential, and other uses in the existing central business district. Intended to aid in the revitalization of Arlington''s original downtown area, and to establish an identity for the downtown area by permitting uses that enhance its role as a unique civic and ceremonial heart of the City.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Parking minimums reduced, on-street parking may count towards minimums. Surface parking lots not screened by buildings must be screened from public streets by a three-foot high masonry fence within a five-foot wide landscaping bed.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'db' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington') AND pu.name IN ('Downtown, civic, service, office, institutional, cultural, residential, and other uses', 'Bank or Financial Institution', 'Bar', 'Catering service', 'Restaurant', 'Restaurant, take-out and delivery only', 'Sidewalk cafe', 'Mixed-use development or building (Specific Use Permit)', 'Office, business or professional', 'General personal services', 'Alternative Financial Institution (Specific Use Permit)', 'Day care center (Specific Use Permit)', 'Restaurant with drive-through (Specific Use Permit)', 'Hotel, luxury', 'Hotel, upper upscale', 'Hotel, upscale (Specific Use Permit)', 'Hotel, upper midscale (Restricted)', 'Hotel, midscale (Restricted)', 'Hotel, economy (Restricted)') ON CONFLICT DO NOTHING;
