-- Gemini-extracted: Corpus Christi, TX
-- Generated: 2026-04-07T22:54:45.344Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Nueces County', 'nueces-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'nueces-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Corpus Christi', 'corpus-christi', 27.8006, -97.3964, 317863) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family detached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Agricultural uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory buildings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Related recreational facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public and civic uses (limited)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home occupations', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouse dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouse units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cottage units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community buildings', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private garages/storage structures', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small restaurants', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail stores', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multifamily uses (max 37 dwelling units per acre)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Financial institutions', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesale distributing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Caretaker''s quarters', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial operations with significant external impacts', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'FR', 'fr', 'Farm Rural District', 'The Farm Rural zoning district includes lands that are relatively underdeveloped and agricultural in nature, intended to permit the continued use of the land for agricultural purposes. It serves as the default zoning for newly-annexed land not yet assigned a final zoning classification.', 35, NULL, 43560, 50, 40, 25, 10, 'Two (2) paved off-street parking spaces per dwelling unit on the same lot.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'fr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Single-family detached dwellings', 'Agricultural uses', 'Accessory buildings') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'RE', 're', 'Residential Estate District', 'The Residential Estate zoning district provides for single-family residential development of a spacious character with related recreational facilities, aiming to create an orderly, attractive, and spacious residential living environment. Lots are a minimum of 1 acre and are not intended to be served by City water, wastewater, or stormwater services, retaining a rural character.', 35, NULL, 43560, 50, 30, 20, 10, 'Two (2) paved off-street parking spaces per dwelling unit on the same lot.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 're' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Single-family detached dwellings', 'Related recreational facilities', 'Accessory buildings') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'RS-6', 'rs-6', 'Single-Family 6 District', 'The Single-Family 6 zoning district provides for orderly suburban residential development and redevelopment, allowing a limited number of public and civic uses to preserve the single-family character of the neighborhood. The numerical value relates to the minimum lot size.', 35, NULL, 6000, 50, 25, 20, 5, 'Two (2) paved off-street parking spaces per dwelling unit on the same lot.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Single-family detached dwellings', 'Public and civic uses (limited)', 'Home occupations') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'RS-TH', 'rs-th', 'Townhouse District', 'The Townhouse zoning district allows for smaller dwelling units than typically found in single-family districts, suitable for infill development and as a transition area between residential and nonresidential zones. Townhouse developments may be platted as fee-simple lots or condominiums.', 35, NULL, NULL, 50, 20, 20, 5, 'Two (2) paved off-street parking spaces plus a one-car garage for each dwelling unit on the same lot.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rs-th' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Townhouse dwellings', 'Two-family dwellings', 'Accessory buildings') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'RM-1', 'rm-1', 'Multifamily 1 District', 'The Multifamily 1 zoning district provides for a variety of housing types at multifamily densities, appropriate for areas with convenient access to collector and arterial streets, and nearby civic, commercial, and employment opportunities.', 35, NULL, NULL, NULL, 25, 20, 10, '1.5 spaces per 0/1 bedroom unit, 2.0 spaces per 2 bedroom unit, 2.5 spaces per 3+ bedroom unit; average of not less than 2 spaces per unit for total development.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Single-family detached dwellings', 'Two-family dwellings', 'Townhouse units', 'Apartment units') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'CH', 'ch', 'Cottage Housing District', 'The Cottage Housing District promotes a traditional neighborhood development pattern to maintain and enhance existing small-city character, creating small communities of cottages around common open space. It allows for higher residential density than typical single-family zones through smaller homes, reduced setbacks, and clustered parking.', NULL, NULL, 21780, 65, 10, 5, 0, '1.25 spaces per unit for dwellings under 1,000 sq ft; 1.5 spaces per unit for dwellings 1,000-1,400 sq ft.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ch' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Cottage units', 'Community buildings', 'Private garages/storage structures') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'CN-1', 'cn-1', 'Neighborhood Commercial 1 District', 'The Neighborhood Commercial 1 zoning district provides areas for commercial activity, such as convenience goods and personal services, that primarily benefit nearby residential areas. These areas are generally located within neighborhoods with pedestrian access to adjacent residential areas.', 35, NULL, NULL, NULL, 25, 10, 5, 'One (1) parking space for each 200 square feet of floor area, with a minimum of 3 spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'cn-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Small restaurants', 'Retail stores', 'Professional offices', 'Multifamily uses (max 37 dwelling units per acre)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'ON', 'on', 'Neighborhood Office District', 'The Neighborhood Office zoning district provides a location for office development with relatively low traffic generation. Areas in this district may be appropriate adjacent to most residential uses and as a transition between residential and nonresidential areas.', 35, NULL, NULL, NULL, 25, 10, 5, 'One (1) parking space for each 300 square feet of floor area, with a minimum of 3 spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'on' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Professional offices', 'Medical offices', 'Financial institutions') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'IL', 'il', 'Light Industrial District', 'The Light Industrial zoning district accommodates light manufacturing, fabricating, warehousing, and wholesale distributing in buildings with access by major arterials, freeways, or railroads. Uses are limited to those not objectionable by reason of odor, dust, smoke, noise, or vibration.', 100, NULL, 5000, 90, 25, 5, 5, 'One (1) space per 500 sq ft of floor area for manufacturing/research; one (1) space per 1,000 sq ft for warehouses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'il' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Light manufacturing', 'Warehousing', 'Wholesale distributing', 'Caretaker''s quarters') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'corpus-christi'), 'IH', 'ih', 'Heavy Industrial District', 'The Heavy Industrial zoning district provides for industrial operations of all types that may be noxious or offensive due to odors, smoke, dust, noise, fumes, or vibrations. This district is intended to serve the entire community and is not appropriate adjacent to a residential zoning district.', 100, NULL, 5000, 90, 25, 5, 5, 'One (1) space per 500 sq ft of floor area for manufacturing/research; one (1) space per 1,000 sq ft for warehouses.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ih' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi') AND pu.name IN ('Heavy manufacturing', 'Industrial operations with significant external impacts', 'Caretaker''s quarters') ON CONFLICT DO NOTHING;
