-- Gemini-extracted: San Antonio, TX
-- Generated: 2026-04-07T22:50:12.871Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Bexar County', 'bexar-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'San Antonio', 'san-antonio', 29.4241, -98.4936, 1451853) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwelling (detached)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Foster family home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public school', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private school', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multi-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwelling (detached, attached or townhouse)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Two-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Three-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Four-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Row-house or zero-lot line dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Assisted living home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('College fraternity dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('School dormitory', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Church', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Animal and pet services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Fitness/health club', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Antique store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apparel and accessory store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bookstore', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bakery', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Florist', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Gift shop', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional offices', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Music store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Convenience store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurant', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Pet Grooming', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Candy, Nut and Confectionery (retail)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Video Games', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small Animal Clinic', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartments (maximum of 6 units per gross acre)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Furniture Sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Nursery (retail - no growing of plants on site permitted)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office Equipment and Supply', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Rug or Carpet Sales (retail)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Alcoholic Beverage Retail Store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Miniature Golf', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Billiard Parlor (no alcohol)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Lazer Hide and Seek Game (indoors)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Pet Cemetery', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Auto Alarm and Radio - Sales and Installation', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cabinet/Carpenter Shop', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Can Recycle Collection Station (no shredding)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Lumber Yard and Building Materials', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Machine Shop', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Broom and Brush Manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Abrasive Manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Chemical/Drug Wholesale and Storage', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Clothing Manufacturing (non-Chemical Process)', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Ice Cream Manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Indoor Theatres', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Taxi Service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartments (6 dwelling units through 50 dwelling units per gross acre)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Motels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices (no restrictions on square footage unless otherwise prescribed)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Telephone Equipment Infrastructure', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'R-6', 'r-6', 'Residential Single-Family District', 'This district is primarily for detached single-family dwellings, foster family homes, and public and private schools, with a minimum lot size of 6,000 square feet.', 35, NULL, 6000, NULL, 20, 10, 5, '1 space per dwelling unit') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Single-family dwelling (detached)', 'Foster family home', 'Public school', 'Private school') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'R-5', 'r-5', 'Residential Single-Family District', 'This district accommodates detached single-family dwellings on slightly smaller lots, with a minimum lot size of 5,000 square feet.', 35, NULL, 5000, NULL, 20, 10, 5, '1 space per dwelling unit') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Single-family dwelling (detached)', 'Foster family home', 'Public school', 'Private school') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'R-4', 'r-4', 'Residential Single-Family District', 'This district allows for single-family dwellings on small lots, with a minimum lot size of 4,000 square feet, and includes foster family homes and schools.', 35, NULL, 4000, NULL, 20, 10, 5, '1 space per dwelling unit') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Single-family dwelling (detached)', 'Foster family home', 'Public school', 'Private school') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'MF-25', 'mf-25', 'Low Density Multi-Family District', 'This district provides for multi-family residential units with a maximum density of 25 units per acre, accommodating apartments, townhouses, and condominiums.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Subject to UDC regulations') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mf-25' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Multi-family dwelling', 'Single-family dwelling (detached, attached or townhouse)', 'Two-family dwelling', 'Three-family dwelling', 'Four-family dwelling', 'Row-house or zero-lot line dwelling', 'Assisted living home', 'College fraternity dwelling', 'School dormitory', 'Church', 'Foster family home', 'Public school', 'Private school') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'NC', 'nc', 'Neighborhood Commercial District', 'This district provides small areas for offices, professional services, and storefront retail uses, designed to be in scale with surrounding residential development, with individual building sizes limited to 3,000 square feet.', 35, NULL, NULL, NULL, 0, NULL, NULL, '1 space per dwelling unit (for mixed-use residential component), subject to UDC regulations for commercial uses') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Animal and pet services', 'Fitness/health club', 'Antique store', 'Apparel and accessory store', 'Bookstore', 'Bakery', 'Florist', 'Gift shop', 'Professional offices', 'Music store', 'Convenience store', 'Restaurant', 'Pet Grooming', 'Candy, Nut and Confectionery (retail)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'C-2', 'c-2', 'Commercial District', 'This district accommodates commercial and retail uses that are more intensive than neighborhood commercial, generating a greater volume of vehicular traffic.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Subject to UDC regulations') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'c-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Video Games', 'Small Animal Clinic', 'Apartments (maximum of 6 units per gross acre)', 'Furniture Sales', 'Nursery (retail - no growing of plants on site permitted)', 'Office Equipment and Supply', 'Rug or Carpet Sales (retail)', 'Alcoholic Beverage Retail Store', 'Miniature Golf', 'Billiard Parlor (no alcohol)', 'Lazer Hide and Seek Game (indoors)', 'Pet Cemetery') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'L', 'l', 'Light Industrial District', 'This district provides for a mix of light manufacturing uses, office parks, flex-space, and limited retail and service uses that support industrial development.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'l' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Auto Alarm and Radio - Sales and Installation', 'Cabinet/Carpenter Shop', 'Can Recycle Collection Station (no shredding)', 'Lumber Yard and Building Materials', 'Machine Shop', 'Broom and Brush Manufacturing') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'I-1', 'i-1', 'General Industrial District', 'This district accommodates general industrial activities, including fabrication, manufacturing, and other industrial uses.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'i-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Abrasive Manufacturing', 'Chemical/Drug Wholesale and Storage', 'Clothing Manufacturing (non-Chemical Process)', 'Ice Cream Manufacturing') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'RM-4', 'rm-4', 'Residential Mixed District', 'This district allows for a variety of residential types including single-family (detached, attached, townhouse), two-family, three-family, four-family, row-house, zero-lot line dwellings, and accessory dwellings, with a minimum lot size of 4,000 square feet.', 35, NULL, 4000, NULL, 15, 10, 5, 'Subject to UDC regulations') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'rm-4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Single-family dwelling (detached, attached or townhouse)', 'Two-family dwelling', 'Three-family dwelling', 'Four-family dwelling', 'Row-house or zero-lot line dwelling', 'Accessory dwelling', 'Public school', 'Private school') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'san-antonio'), 'D', 'd', 'Downtown District', 'This district provides for concentrated downtown retail, service, office, and mixed uses within the central business district, with no building size or height limitations and waived parking requirements.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Waived') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio') AND pu.name IN ('Indoor Theatres', 'Taxi Service', 'Apartments (6 dwelling units through 50 dwelling units per gross acre)', 'Hotels', 'Motels', 'Offices (no restrictions on square footage unless otherwise prescribed)', 'Telephone Equipment Infrastructure') ON CONFLICT DO NOTHING;
