-- Gemini-extracted: Lubbock, TX
-- Generated: 2026-04-07T22:57:30.225Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Lubbock County', 'lubbock-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'lubbock-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Lubbock', 'lubbock', 33.5779, -101.8552, 263930) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Agricultural Uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Garden', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Farm, Ranch, or Orchard', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-Family Detached Dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrialized Housing', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Utilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Water Storage', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Storm Shelter', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-Family Garden Home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-Family Cottage', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouse', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live-Work Unit', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Art Gallery', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bakery', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bank/Financial Institution', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Barber/Beauty Shop', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bookstore', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Cafe/Coffee Shop', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Child Care Center', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Center', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Library', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office, General', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurant, Full Service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail Sales, General', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Grocery (Food Sales)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automobile Sales/Rental', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Automobile Service/Repair', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Car Wash', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Convenience Store', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Drive-Through Restaurant', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Gas Station', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel/Motel', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Building Material Sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Contractor''s Office/Yard', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy Equipment Sales/Rental', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouse', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesale Trade', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Assembly, Light', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Distribution Center', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Manufacturing, Light', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Research and Development', 'Industrial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'RE', 're', 'Residential Estates', 'Provides for very low-density residential neighborhoods with on-site utilities, preserving rural low-density character and allowing for large animals. It also includes a cluster option for residential neighborhoods with a high percentage of common open space to maintain rural character.', 45, NULL, 87120, 50, 60, 30, 20, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 're' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Agricultural Uses', 'Community Garden', 'Farm, Ranch, or Orchard', 'Single-Family Detached Dwelling', 'Industrialized Housing', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'SF-1', 'sf-1', 'Very Low Density Single-Family', 'Provides for neighborhoods of large to moderately sized lots, each with a single-family detached dwelling and access from a street that is internal to the development. Characterized by lots smaller than estate with shallower setbacks, curvilinear streets, and cul-de-sacs.', 35, NULL, 21780, NULL, 25, 20, 10, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'sf-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Industrialized Housing', 'Community Garden', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'SF-2', 'sf-2', 'Low Density Single-Family', 'Provides for single-family detached, cottage, or garden homes on public utilities with open space provided on private lots. Annexed land is zoned SF-2 by default.', NULL, NULL, 5000, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'sf-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Single-Family Garden Home', 'Single-Family Cottage', 'Duplex', 'Townhouse', 'Multiplex', 'Industrialized Housing', 'Community Garden', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'MDR', 'mdr', 'Medium Density Residential', 'Provides for mixed housing types, including townhouses, detached single-family garden homes, and low- to mid-rise apartments, located in a village development or adjacent to a mixed-use district or center. Buildings are typically in close proximity to the street edge.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mdr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Single-Family Garden Home', 'Single-Family Cottage', 'Duplex', 'Townhouse', 'Multiplex', 'Apartment', 'Industrialized Housing', 'Community Garden', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'HDR', 'hdr', 'High Density Residential', 'Provides for mid- to high-rise apartment development in a mixed-use district or center. Additional density may be allowed for apartments, multiplexes, townhouses, and live-work units with a Specific Use Permit.', 45, NULL, 900, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'hdr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Single-Family Garden Home', 'Single-Family Cottage', 'Duplex', 'Townhouse', 'Multiplex', 'Apartment', 'Live-Work Unit', 'Industrialized Housing', 'Community Garden', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'NC', 'nc', 'Neighborhood Commercial', 'Provides for small-scale retail and moderate density residential uses located away from major intersections, with building and site design standards compatible with adjacent residential uses.', NULL, NULL, 1000, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Duplex', 'Townhouse', 'Multiplex', 'Apartment', 'Art Gallery', 'Bakery', 'Bank/Financial Institution', 'Barber/Beauty Shop', 'Bookstore', 'Cafe/Coffee Shop', 'Child Care Center', 'Community Center', 'Library', 'Medical Office', 'Office, General', 'Restaurant, Full Service', 'Retail Sales, General', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'AC', 'ac', 'Auto-Urban Commercial', 'Provides for a broad range of single-use and multi-tenant centers with retail, service, and office uses, typically with on-site surface parking. Located along major thoroughfares or at nodes with increased intensity.', NULL, NULL, NULL, NULL, 40, NULL, 15, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ac' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Grocery (Food Sales)', 'Automobile Sales/Rental', 'Automobile Service/Repair', 'Bank/Financial Institution', 'Car Wash', 'Convenience Store', 'Drive-Through Restaurant', 'Gas Station', 'Hotel/Motel', 'Office, General', 'Retail Sales, General', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'OF', 'of', 'Office', 'Provides for development of centers for professional employment. Can be used as a transition between more intense uses and residential uses with site and building compatibility required.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'of' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Office, General', 'Medical Office', 'Bank/Financial Institution', 'Child Care Center', 'Community Center', 'Library', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'HC', 'hc', 'Heavy Commercial', 'Provides for heavy vehicle repair, wholesale trade, and warehousing and freight movement uses, typically with outside storage. Should be located away from residential areas or heavily buffered.', NULL, NULL, 10000, NULL, 40, NULL, 30, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'hc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Grocery (Food Sales)', 'Automobile Service/Repair', 'Building Material Sales', 'Contractor''s Office/Yard', 'Heavy Equipment Sales/Rental', 'Warehouse', 'Wholesale Trade', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'LI', 'li', 'Light Industrial', 'Provides for industrial uses (non-retail) less intensive than Heavy Industrial, including office, warehousing, distribution, and light assembly, with operations conducted indoors without creating smoke, gas, odor, dust, soot, or other noxious elements.', NULL, NULL, 20000, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.03.009-2 Off-Street Parking and Loading Schedule.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'li' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Assembly, Light', 'Distribution Center', 'Manufacturing, Light', 'Office, General', 'Research and Development', 'Warehouse', 'Wholesale Trade', 'Utilities', 'Water Storage', 'Storm Shelter') ON CONFLICT DO NOTHING;
