-- Gemini-extracted: Lubbock, TX
-- Generated: 2026-04-07T22:12:06.941Z
-- Zones: 10
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Lubbock County', 'lubbock-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'lubbock-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Lubbock', 'lubbock', 33.5779, -101.8552, 263930) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-Family Detached Dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Farm, Ranch, or Orchard', 'Agricultural') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Garden', 'Agricultural') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Park & Recreation Facility or Center', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-Family Garden Home', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouse', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live-Work Unit', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail Sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Personal Services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Professional Office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical and Diagnostic Laboratories', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Financial Services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing and Storage', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light Manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Wholesale Trade', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy Manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Freight Movement', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Resource Extraction', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential Dwelling Units', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Eating and Drinking Establishments', 'Commercial') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'RE', 're', 'Residential Estates', 'This district provides for very low-density residential neighborhoods with on-site utilities, preserving a rural low-density character and allowing for large animals. It also accommodates residential neighborhoods with a high percentage of common open space.', 45, NULL, 87120, 35, 60, 30, 20, 'Refer to UDC Table 39.02.004.a-3 (RE Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 're' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Farm, Ranch, or Orchard', 'Community Garden') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'SF-1', 'sf-1', 'Very Low Density Single-Family', 'This district is intended for neighborhoods with large to moderately sized lots, each with a single-family detached dwelling and internal street access. It also allows for clustering of moderately sized lots with common open space.', 35, NULL, 21700, 45, 25, 20, 10, 'Refer to UDC Table 39.02.004.b-3 (SF-1 Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'sf-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Community Garden', 'Park & Recreation Facility or Center') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'SF-2', 'sf-2', 'Low Density Single-Family', 'This district provides for smaller to moderately-sized lots for single-family detached dwellings on public utilities, with open space located on private lots. It is also the default zoning for annexed lands.', NULL, NULL, 5000, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.02.004.c-3 (SF-2 Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'sf-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Single-Family Detached Dwelling', 'Single-Family Garden Home', 'Duplex') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'MDR', 'mdr', 'Medium Density Residential', 'This district is established to provide for a village neighborhood environment of smaller-sized lots, accommodating attached dwellings such as duplexes, townhouses, and multiplexes.', NULL, NULL, 1400, 45, NULL, NULL, NULL, 'Refer to UDC Table 39.02.004.d-3 (MDR Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mdr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Duplex', 'Townhouse', 'Multiplex', 'Community Garden') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'HDR', 'hdr', 'High Density Residential', 'This district is intended for mid- to high-rise apartment development in a mixed-use district or center, including detached single-family garden homes, live-work buildings, and other vertically mixed-use buildings with urban open space.', NULL, NULL, 700, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.02.004.e-3 (HDR Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'hdr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Apartment', 'Multiplex', 'Live-Work Unit') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'NC', 'nc', 'Neighborhood Commercial', 'This district provides for a broad range of single-use and multi-tenant centers with retail, service, and office uses, typically with on-site surface parking. It may be located along major thoroughfares or at nodes with increased intensity.', NULL, NULL, 1000, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.02.006.a-3 (NC Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'nc' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Retail Sales', 'Personal Services', 'Professional Office') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'OF', 'of', 'Office', 'This district is intended for the development of centers for professional employment and can serve as a transition between more intense uses and residential areas, requiring site and building compatibility with adjacent residential uses.', NULL, NULL, 1000, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.02.006.b-2 (OF Lot Intensity and Dimensions) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'of' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Professional Office', 'Medical and Diagnostic Laboratories', 'Financial Services') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'LI', 'li', 'Light Industrial', 'This district provides for industrial uses (non-retail) that are less intensive than General Industrial, including office, warehousing, distribution, and light assembly, with operations primarily indoors without creating noxious elements.', NULL, NULL, 20000, NULL, 40, NULL, 100, 'Refer to UDC Table 39.02.006.f-3 (LI Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'li' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Warehousing and Storage', 'Light Manufacturing', 'Wholesale Trade') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'GI', 'gi', 'General Industrial', 'This district accommodates more intensive industrial uses, including manufacturing, processing, and heavy equipment operations, which may have outdoor activities and a greater impact on the surrounding environment.', 140, NULL, 130680, NULL, NULL, NULL, NULL, 'Refer to UDC Table 39.02.006.g-3 (GI Off-Street Parking and Loading Schedule) and Division 3.3 (Parking, Loading, Stacking, and Access).') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'gi' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Heavy Manufacturing', 'Freight Movement', 'Resource Extraction') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'lubbock'), 'MU', 'mu', 'Mixed-Use Districts (General)', 'These districts permit both residential and nonresidential principal uses, either vertically within the same structure or horizontally on the same lot, to encourage vibrant, walkable communities.', NULL, NULL, 1000, NULL, NULL, NULL, NULL, 'Parking and loading space requirements in Table 39.03.009-2 (Off-Street Parking and Loading Schedule) do not apply in Base Mixed-Use Districts; however, if parking is voluntarily provided, design requirements apply. Off-site parking is permitted within 300 feet.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'mu' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock') AND pu.name IN ('Residential Dwelling Units', 'Retail Sales', 'Professional Office', 'Eating and Drinking Establishments') ON CONFLICT DO NOTHING;
