-- Gemini-extracted: Laredo, TX
-- Generated: 2026-04-07T22:59:12.667Z
-- Zones: 11
PRAGMA foreign_keys = ON;

INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX') ON CONFLICT (slug) DO NOTHING;
INSERT INTO counties (state_id, name, slug) VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Webb County', 'webb-county') ON CONFLICT (state_id, slug) DO NOTHING;
INSERT INTO cities (county_id, name, slug, latitude, longitude, population) VALUES ((SELECT id FROM counties WHERE slug = 'webb-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')), 'Laredo', 'laredo', 27.5036, -99.5076, 255205) ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwelling', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day care centers', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Golf courses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parks, public and private', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public and quasi-public uses', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public utility facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Schools, public and private', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family residential subdivisions', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public uses normally considered an integral part of the residential neighborhood', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Single-family dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Condominiums', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplexes, triplexes and multiple-family structures (apartments)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouses, townhomes and condominium clusters', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Offices, clubhouses and recreational facilities related to the principal use', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants and cafes (conditional)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex and single-family attached dwellings', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Multiple-family dwellings and dwelling groups', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Boardinghouses and rooming houses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public schools, parochial schools, kindergartens', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public parks and recreational facilities', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Churches and similar religious institutions', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Developer''s project office and sales office', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential facilities', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential homes', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Rest homes, nursing homes and convalescent homes (conditional)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Private recreational uses and facilities (conditional)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Mobile home parks (conditional)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurants serving alcohol (with SUP)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business and commercial development serving a limited geographic area or neighborhood', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex (Horizontal)', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Trade or Business School (conditional)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail sale of hardware and remodeling supplies', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Nationalization/"nacionalizacion" of vehicles enterprise (with SUP)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Sign painting shops', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Monument sales and service shops', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Funeral homes and Chapels', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Small animal veterinary clinics', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Any nonresidential use permitted in the B-3 District (without floor area square footage limitation)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Agricultural sales and services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Heavy automotive sales and service', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Building Material and Equipment Sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Business or Trade School', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Communications Services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Construction Services', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Night clubs, bars, saloons, cantinas, billiard parlors, or carnivals (300+ feet from R District)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Theaters, bingo parlors, bowling alleys, and similar enterprises (75+ feet from R-District)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Exterminating Services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Amusement Redemption Machine Establishment', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Halfway Houses (Criminal)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses are prohibited unless specifically permitted', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehousing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Industrial uses', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Bars, night clubs, cantinas, saloons, billiard parlors, and carnivals (prohibited within 300 feet of any residential district)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Arts and entertainment venues', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Commercial uses', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Residential uses', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office uses', 'Mixed-Use') ON CONFLICT (name, category) DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'R-1', 'r-1', 'Single Family Residential District', 'The principal purpose of the R-1 district is to conserve and protect single-family residential development, providing for neighborhoods of single-family homes with a variety of lot sizes and dimensions.', 35, NULL, 6000, NULL, 20, 6, 5, 'Two paved off-street parking spaces on the same lot as the main building.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Single-family dwelling', 'Churches', 'Day care centers', 'Golf courses', 'Parks, public and private', 'Public and quasi-public uses', 'Public utility facilities', 'Schools, public and private', 'Single-family residential subdivisions') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'R-1A', 'r-1a', 'Single Family Reduced Area District', 'This district provides for single-family residential development on smaller lots than R-1, allowing for a reduced area per dwelling unit.', 35, NULL, 4500, NULL, 20, 6, 5, 'Two paved off-street parking spaces on the same lot as the main building.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1a' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Single-family dwelling') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'R-1B', 'r-1b', 'Single Family High Density District', 'The purpose of R-1B zoning districts is to provide for residential uses and those public uses normally considered an integral part of the residential neighborhood they serve, allowing for the subdivision of single-family residential lots with a minimum of 3,000 square feet.', 35, NULL, 3000, NULL, 20, 6, 5, 'Two paved off-street parking spaces on the same lot as the main building.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-1b' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Single-family dwelling', 'Public uses normally considered an integral part of the residential neighborhood') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'R-2', 'r-2', 'Multi-Family Residential District', 'The purpose of the R-2 district is to provide for medium- to high-density housing in multiple-family structures and their directly related complementary and accessory uses, designed to allow economical use of land while creating an attractive, functional and safe residential environment.', 50, NULL, 6000, NULL, 20, 6, 5, 'Two paved off-street parking spaces plus a one-car garage for each dwelling unit for duplex, triplex, fourplex, and townhouse dwellings.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Single-family dwellings', 'Condominiums', 'Duplexes, triplexes and multiple-family structures (apartments)', 'Townhouses, townhomes and condominium clusters', 'Churches', 'Day care centers', 'Golf courses', 'Parks, public and private', 'Public and quasi-public uses', 'Public utility facilities', 'Offices, clubhouses and recreational facilities related to the principal use', 'Restaurants and cafes (conditional)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'R-3', 'r-3', 'Mixed Residential District', 'The R-3 district is intended to provide opportunities for the development of attractive living environments at densities greater than permitted in other residential districts, encouraging high-density development of affordable single-family and multiple-family housing types.', 50, NULL, 6000, NULL, 20, 6, 5, 'Duplex and multiple-family dwellings require specific parking, generally two paved off-street parking spaces plus a one-car garage for each dwelling unit for duplexes.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Duplex and single-family attached dwellings', 'Multiple-family dwellings and dwelling groups', 'Boardinghouses and rooming houses', 'Public schools, parochial schools, kindergartens', 'Public parks and recreational facilities', 'Churches and similar religious institutions', 'Developer''s project office and sales office', 'Residential facilities', 'Residential homes', 'Rest homes, nursing homes and convalescent homes (conditional)', 'Private recreational uses and facilities (conditional)', 'Mobile home parks (conditional)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'R-O', 'r-o', 'Residential-Office District', 'This district is intended to provide for a transition between residential and more intensive commercial uses, allowing for a mix of residential and office uses. Establishments shall not exceed 3,000 square feet in floor area.', 50, NULL, 6000, NULL, 20, 6, 5, 'Parking requirements vary based on use. Office and professional buildings generally require one parking space for each 300 square feet of floor area, with a minimum of 3 spaces. Front yard shall not be used for parking except for the driveway.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'r-o' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Residential uses', 'Office uses', 'Restaurants serving alcohol (with SUP)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'B-1', 'b-1', 'Limited Business District', 'The purpose of the B-1 limited business district is to provide for business and commercial development serving a limited geographic area or neighborhood.', 45, NULL, 6000, NULL, 25, 10, 10, 'Commercial and retail uses generally require one parking space for each 200 square feet of floor area, with a minimum of 3 spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Business and commercial development serving a limited geographic area or neighborhood', 'Duplex (Horizontal)', 'Restaurants serving alcohol (with SUP)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'B-3', 'b-3', 'Community Business District', 'This district provides for general business and commercial development, serving a wider community area.', 160, NULL, 10000, NULL, 25, 10, 10, 'Commercial and retail uses generally require one parking space for each 200 square feet of floor area, with a minimum of 3 spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Trade or Business School (conditional)', 'Retail sale of hardware and remodeling supplies', 'Nationalization/"nacionalizacion" of vehicles enterprise (with SUP)', 'Sign painting shops', 'Monument sales and service shops', 'Funeral homes and Chapels', 'Small animal veterinary clinics', 'Duplex (Horizontal)', 'Restaurants serving alcohol (with SUP)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'B-4', 'b-4', 'Highway Commercial District', 'This district provides for commercial and industrial land uses with good access and high visibility, designed to create compatibility between diverse uses and adjacent zoning districts, often along major highways.', NULL, NULL, 9000, NULL, 25, 10, 10, 'Commercial and retail uses generally require one parking space for each 200 square feet of floor area, with a minimum of 3 spaces.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'b-4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Any nonresidential use permitted in the B-3 District (without floor area square footage limitation)', 'Agricultural sales and services', 'Heavy automotive sales and service', 'Building Material and Equipment Sales', 'Business or Trade School', 'Communications Services', 'Construction Services', 'Night clubs, bars, saloons, cantinas, billiard parlors, or carnivals (300+ feet from R District)', 'Theaters, bingo parlors, bowling alleys, and similar enterprises (75+ feet from R-District)', 'Exterminating Services', 'Amusement Redemption Machine Establishment', 'Halfway Houses (Criminal)', 'Nationalization/"nacionalizacion" of vehicles enterprise (with SUP)', 'Residential uses are prohibited unless specifically permitted') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'M-1', 'm-1', 'Light Manufacturing District', 'This district provides for light manufacturing, warehousing, and industrial uses, typically with less intensive impacts than heavy manufacturing. It includes distance regulations to prevent certain entertainment venues near residential districts.', NULL, NULL, 30000, NULL, 25, 10, 10, 'Parking requirements will be based on the specific industrial use. Industrial parking lots over 1 acre have specific design standards.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Light manufacturing', 'Warehousing', 'Industrial uses', 'Nationalization/"nacionalizacion" of vehicles enterprise (with SUP)', 'Bars, night clubs, cantinas, saloons, billiard parlors, and carnivals (prohibited within 300 feet of any residential district)') ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement) VALUES ((SELECT id FROM cities WHERE slug = 'laredo'), 'AE', 'ae', 'Arts And Entertainment District', 'The purpose of the AE District is to provide a mixed-use environment where arts and entertainment venues, commercial, residential and office uses harmoniously co-exist in a higher density, pedestrian-oriented environment.', NULL, NULL, 6000, NULL, 25, 10, 10, 'Exempt from off-street parking requirements.') ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;
INSERT INTO zone_permitted_uses (zone_id, permitted_use_id) SELECT z.id, pu.id FROM zones z, permitted_uses pu WHERE z.zone_code_slug = 'ae' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo') AND pu.name IN ('Arts and entertainment venues', 'Commercial uses', 'Residential uses', 'Office uses', 'Duplex (Horizontal)') ON CONFLICT DO NOTHING;
