name = "zoningbase"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "zoningbase-prod"
database_id = "90c59268-dd2d-4074-af1a-ecdab443d79c"
