-- ZoningBase Texas Seed Data
-- Auto-generated by scripts/generate-texas-seeds.mjs
-- Generated: 2026-04-07T20:52:28.645Z
-- Cities: San Antonio, Dallas, Fort Worth, El Paso, Arlington, Corpus Christi, Plano, Lubbock, Laredo

PRAGMA foreign_keys = ON;

-- State: Texas
INSERT INTO states (name, slug, abbreviation) VALUES ('Texas', 'texas', 'TX')
  ON CONFLICT (slug) DO NOTHING;

-- Permitted Uses (all unique)
INSERT INTO permitted_uses (name, category) VALUES ('Single-Family Detached', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Home Occupation', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Accessory Dwelling Unit', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Place of Worship', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Public Park', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Townhouse', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day Care (Home)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Apartment', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Condominium', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Assisted Living', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Day Care (Commercial)', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Retail Sales', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Restaurant (General)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Office (General)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Personal Services', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Entertainment (Indoor)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Drive-Through Facility', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Parking Facility (Commercial)', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Light Manufacturing', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Warehouse', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Distribution Center', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Flex Space', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Live-Work Unit', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Community Garden', 'Civic') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Group Residential', 'Residential') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Medical Clinic', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Hotel', 'Commercial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Data Center', 'Industrial') ON CONFLICT (name, category) DO NOTHING;
INSERT INTO permitted_uses (name, category) VALUES ('Duplex', 'Residential') ON CONFLICT (name, category) DO NOTHING;

-- ── San Antonio (Bexar County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Bexar County', 'bexar-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'San Antonio', 'san-antonio', 29.4241, -98.4936, 1451853
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'san-antonio' AND county_id = (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-4', 'r-4', 'Residential Single-Family', 'Low-density single-family residential district. Permits detached single-family dwellings, home occupations, and accessory structures.',
    35, 0.4, 6000, 45,
    25, 5, 5, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-4' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Accessory Dwelling Unit', 'Place of Worship', 'Public Park')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'san-antonio' AND county_id = (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-6', 'r-6', 'Residential Single-Family (High Density)', 'Higher-density single-family residential district allowing smaller lots and zero-lot-line configurations.',
    35, 0.65, 4000, 55,
    20, 5, 0, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio')
    AND pu.name IN ('Single-Family Detached', 'Townhouse', 'Home Occupation', 'Day Care (Home)')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'san-antonio' AND county_id = (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'MF-33', 'mf-33', 'Multi-Family (33 units/acre)', 'Multi-family residential district allowing up to 33 dwelling units per acre. Permits apartments, condominiums, and assisted living facilities.',
    45, 1.2, 10000, 70,
    25, 15, 10, '1.5 spaces per 1BR unit, 2 spaces per 2BR+ unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'mf-33' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse', 'Assisted Living', 'Day Care (Commercial)')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'san-antonio' AND county_id = (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'C-2', 'c-2', 'Commercial', 'General commercial district for retail, service, office, and entertainment uses. Drive-through facilities permitted with conditional use.',
    45, 1.5, 5000, 85,
    0, 0, 0, '1 space per 250 sqft for retail; 1 per 200 sqft for office.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'c-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Office (General)', 'Personal Services', 'Entertainment (Indoor)', 'Drive-Through Facility', 'Parking Facility (Commercial)')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'san-antonio' AND county_id = (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'I-1', 'i-1', 'General Industrial', 'Light industrial district for manufacturing, warehousing, and distribution. Buffers required adjacent to residential districts.',
    60, 2, 10000, 90,
    25, 10, 10, '1 space per 500 sqft of gross floor area.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'i-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio')
    AND pu.name IN ('Light Manufacturing', 'Warehouse', 'Distribution Center', 'Office (General)', 'Flex Space')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'san-antonio' AND county_id = (SELECT id FROM counties WHERE slug = 'bexar-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'MXD', 'mxd', 'Mixed-Use District', 'Promotes pedestrian-oriented mixed-use development combining residential, commercial, and civic uses in a single district or structure.',
    75, 3, 5000, 90,
    0, 10, 0, 'Residential: 1 per unit. Commercial: 1 per 350 sqft. Shared parking reductions available.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'mxd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'san-antonio')
    AND pu.name IN ('Apartment', 'Retail Sales', 'Restaurant (General)', 'Office (General)', 'Live-Work Unit', 'Public Park')
  ON CONFLICT DO NOTHING;

-- ── Dallas (Dallas County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Dallas County', 'dallas-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'dallas-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Dallas', 'dallas', 32.7767, -96.797, 1304379
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'dallas' AND county_id = (SELECT id FROM counties WHERE slug = 'dallas-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-7.5(A)', 'r-7-5-a', 'Single-Family Residential 7,500 sqft', 'Standard single-family residential district requiring a minimum 7,500 sqft lot. The most common residential zoning in Dallas.',
    30, 0.5, 7500, 45,
    25, 5, 5, '2 enclosed off-street spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-7-5-a' AND z.city_id = (SELECT id FROM cities WHERE slug = 'dallas')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Accessory Dwelling Unit', 'Community Garden')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'dallas' AND county_id = (SELECT id FROM counties WHERE slug = 'dallas-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'MF-2(A)', 'mf-2-a', 'Multifamily Residential', 'Multi-family district allowing apartments, condominiums, and townhomes. Maximum density of approximately 36 units per acre.',
    36, 1, 6000, 60,
    15, 15, 10, '1 space per efficiency, 1.5 per 1BR, 2 per 2BR+.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'mf-2-a' AND z.city_id = (SELECT id FROM cities WHERE slug = 'dallas')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse', 'Group Residential', 'Day Care (Commercial)')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'dallas' AND county_id = (SELECT id FROM counties WHERE slug = 'dallas-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'CR', 'cr', 'Community Retail', 'Community-serving retail and service district. Intended for neighborhood commercial centers with limited hours of operation and minimal external impacts.',
    54, 1, 5000, 80,
    15, 20, 10, '1 space per 200 sqft GFA.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'cr' AND z.city_id = (SELECT id FROM cities WHERE slug = 'dallas')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Personal Services', 'Office (General)', 'Medical Clinic')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'dallas' AND county_id = (SELECT id FROM counties WHERE slug = 'dallas-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'MU-3', 'mu-3', 'Mixed Use 3', 'High-intensity mixed-use district designed for urban centers and transit-oriented development. Permits a wide range of residential, commercial, and institutional uses.',
    240, 10, 3000, 100,
    0, 0, 0, 'Per use type. Reductions available in transit areas.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'mu-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'dallas')
    AND pu.name IN ('Apartment', 'Condominium', 'Retail Sales', 'Restaurant (General)', 'Office (General)', 'Hotel', 'Entertainment (Indoor)', 'Place of Worship')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'dallas' AND county_id = (SELECT id FROM counties WHERE slug = 'dallas-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'IR', 'ir', 'Industrial Research', 'Light industrial and research district for office parks, R&D facilities, clean manufacturing, and data centers.',
    80, 2, 10000, 80,
    30, 20, 15, '1 space per 400 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'ir' AND z.city_id = (SELECT id FROM cities WHERE slug = 'dallas')
    AND pu.name IN ('Office (General)', 'Light Manufacturing', 'Data Center', 'Warehouse', 'Flex Space')
  ON CONFLICT DO NOTHING;

-- ── Fort Worth (Tarrant County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Tarrant County', 'tarrant-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Fort Worth', 'fort-worth', 32.7555, -97.3308, 958692
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'fort-worth' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'A-5', 'a-5', 'One-Family Residential', 'Single-family residential district with minimum 5,000 sqft lots. Standard zoning for established neighborhoods.',
    35, NULL, 5000, 50,
    20, 5, 5, '2 off-street spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'a-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Place of Worship', 'Public Park')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'fort-worth' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'D', 'd', 'Two-Family Residential', 'Duplex and two-family residential district. Permits duplexes, townhomes, and single-family dwellings.',
    35, NULL, 3500, 55,
    20, 5, 5, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'd' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth')
    AND pu.name IN ('Single-Family Detached', 'Duplex', 'Townhouse', 'Home Occupation')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'fort-worth' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'E', 'e', 'Multi-Family Residential', 'Multi-family district for apartments, condominiums, and multi-story residential buildings. Subject to design standards in urban villages.',
    60, NULL, 3000, 65,
    20, 15, 10, '1.5 spaces per 1BR, 2 per 2BR+.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'e' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse', 'Group Residential', 'Assisted Living')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'fort-worth' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'G', 'g', 'Intensive Commercial', 'General commercial district for high-intensity retail, entertainment, and service uses. No residential uses permitted.',
    120, NULL, 5000, 90,
    0, 0, 0, '1 space per 250 sqft for retail; 1 per 100 sqft for restaurants.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'g' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Office (General)', 'Entertainment (Indoor)', 'Hotel', 'Parking Facility (Commercial)')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'fort-worth' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'J', 'j', 'Light Industrial', 'Light industrial district for manufacturing, assembly, warehousing, and distribution. Outdoor storage screened from public rights-of-way.',
    60, NULL, 10000, 85,
    20, 0, 10, '1 space per 500 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'j' AND z.city_id = (SELECT id FROM cities WHERE slug = 'fort-worth')
    AND pu.name IN ('Light Manufacturing', 'Warehouse', 'Distribution Center', 'Flex Space', 'Office (General)')
  ON CONFLICT DO NOTHING;

-- ── El Paso (El Paso County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'El Paso County', 'el-paso-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'el-paso-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'El Paso', 'el-paso', 31.7619, -106.485, 681124
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'el-paso' AND county_id = (SELECT id FROM counties WHERE slug = 'el-paso-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-3', 'r-3', 'Single-Family Residential', 'Low-density single-family district for detached homes on standard lots. ADUs permitted with SUP.',
    30, NULL, 6600, 50,
    20, 5, 5, '2 off-street spaces.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Place of Worship')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'el-paso' AND county_id = (SELECT id FROM counties WHERE slug = 'el-paso-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-5', 'r-5', 'Multi-Family Residential', 'Multi-family residential district permitting apartments, townhomes, and condominiums at moderate to high density.',
    45, NULL, 5000, 65,
    20, 10, 5, '1.5 spaces per unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse', 'Duplex')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'el-paso' AND county_id = (SELECT id FROM counties WHERE slug = 'el-paso-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'C-3', 'c-3', 'General Commercial', 'General commercial district accommodating a broad range of retail, service, office, and entertainment uses.',
    60, NULL, 5000, 85,
    0, 0, 0, '1 space per 250 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'c-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Office (General)', 'Personal Services', 'Drive-Through Facility', 'Entertainment (Indoor)')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'el-paso' AND county_id = (SELECT id FROM counties WHERE slug = 'el-paso-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'M-1', 'm-1', 'Light Manufacturing', 'Light manufacturing and industrial district for clean industry, fabrication, and warehousing.',
    50, NULL, 10000, 80,
    25, 10, 10, '1 space per 500 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'm-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'el-paso')
    AND pu.name IN ('Light Manufacturing', 'Warehouse', 'Distribution Center', 'Office (General)')
  ON CONFLICT DO NOTHING;

-- ── Arlington (Tarrant County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Tarrant County', 'tarrant-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Arlington', 'arlington', 32.7357, -97.1081, 394266
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'arlington' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-5', 'r-5', 'Single-Family District', 'Standard single-family residential district for detached dwellings on minimum 5,000 sqft lots.',
    35, NULL, 5000, 50,
    25, 5, 5, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-5' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Accessory Dwelling Unit')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'arlington' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'MF-22', 'mf-22', 'Multi-Family (22 units/acre)', 'Multi-family residential district with maximum density of 22 dwelling units per acre.',
    45, NULL, 8000, 65,
    25, 20, 15, '1.5 spaces per 1BR, 2 per 2BR+.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'mf-22' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'arlington' AND county_id = (SELECT id FROM counties WHERE slug = 'tarrant-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'LI', 'li', 'Light Industrial', 'Light industrial district for manufacturing, assembly, and distribution with limited external impacts.',
    50, NULL, 10000, 80,
    25, 10, 10, '1 space per 500 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'li' AND z.city_id = (SELECT id FROM cities WHERE slug = 'arlington')
    AND pu.name IN ('Light Manufacturing', 'Warehouse', 'Flex Space', 'Office (General)')
  ON CONFLICT DO NOTHING;

-- ── Corpus Christi (Nueces County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Nueces County', 'nueces-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'nueces-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Corpus Christi', 'corpus-christi', 27.8006, -97.3964, 317863
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'corpus-christi' AND county_id = (SELECT id FROM counties WHERE slug = 'nueces-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'RS-6', 'rs-6', 'Single-Family 6,000 sqft', 'Standard single-family residential district on 6,000 sqft minimum lots.',
    35, NULL, 6000, 50,
    25, 5, 5, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'rs-6' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Accessory Dwelling Unit')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'corpus-christi' AND county_id = (SELECT id FROM counties WHERE slug = 'nueces-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'RM-3', 'rm-3', 'Multi-Family Medium Density', 'Multi-family district for apartments and condominiums at medium density.',
    45, NULL, 6000, 60,
    25, 10, 10, '1.5 spaces per unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'rm-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse', 'Duplex')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'corpus-christi' AND county_id = (SELECT id FROM counties WHERE slug = 'nueces-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'CG-2', 'cg-2', 'General Commercial', 'General commercial district for a wide range of retail, service, and office uses.',
    60, NULL, 5000, 85,
    0, 0, 0, '1 space per 250 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'cg-2' AND z.city_id = (SELECT id FROM cities WHERE slug = 'corpus-christi')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Office (General)', 'Personal Services', 'Hotel')
  ON CONFLICT DO NOTHING;

-- ── Plano (Collin County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Collin County', 'collin-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'collin-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Plano', 'plano', 33.0198, -96.6989, 285494
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'plano' AND county_id = (SELECT id FROM counties WHERE slug = 'collin-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'SF-7', 'sf-7', 'Single-Family 7,200 sqft', 'Single-family residential district with minimum 7,200 sqft lots. The most prevalent residential zoning in Plano.',
    35, 0.45, 7200, 45,
    25, 8, 5, '2 enclosed off-street spaces.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'sf-7' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Community Garden')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'plano' AND county_id = (SELECT id FROM counties WHERE slug = 'collin-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'MF-18', 'mf-18', 'Multi-Family (18 units/acre)', 'Multi-family district allowing up to 18 units per acre. Townhomes, condos, and garden apartments.',
    40, NULL, 10000, 60,
    25, 20, 15, '2 spaces per unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'mf-18' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'plano' AND county_id = (SELECT id FROM counties WHERE slug = 'collin-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'C-1', 'c-1', 'Neighborhood Commercial', 'Small-scale commercial district for neighborhood-serving retail and services.',
    35, 0.5, 5000, 75,
    15, 10, 10, '1 space per 250 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'c-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'plano')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Personal Services', 'Office (General)', 'Medical Clinic')
  ON CONFLICT DO NOTHING;

-- ── Lubbock (Lubbock County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Lubbock County', 'lubbock-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'lubbock-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Lubbock', 'lubbock', 33.5779, -101.8552, 263930
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'lubbock' AND county_id = (SELECT id FROM counties WHERE slug = 'lubbock-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-1', 'r-1', 'Single-Family Residential', 'Low-density single-family residential district. Standard suburban development pattern.',
    35, NULL, 7000, 45,
    25, 5, 5, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Place of Worship')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'lubbock' AND county_id = (SELECT id FROM counties WHERE slug = 'lubbock-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-3', 'r-3', 'Multi-Family Residential', 'Multi-family district for apartments and group housing. Common near Texas Tech University campus.',
    50, NULL, 5000, 65,
    25, 10, 10, '1.5 spaces per unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock')
    AND pu.name IN ('Apartment', 'Condominium', 'Group Residential', 'Duplex')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'lubbock' AND county_id = (SELECT id FROM counties WHERE slug = 'lubbock-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'C-2A', 'c-2a', 'General Commercial', 'General commercial and retail district for community-scale shopping and services.',
    45, NULL, 5000, 80,
    0, 0, 0, '1 space per 250 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'c-2a' AND z.city_id = (SELECT id FROM cities WHERE slug = 'lubbock')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Office (General)', 'Drive-Through Facility', 'Personal Services')
  ON CONFLICT DO NOTHING;

-- ── Laredo (Webb County) ──

INSERT INTO counties (state_id, name, slug)
  VALUES ((SELECT id FROM states WHERE slug = 'texas'), 'Webb County', 'webb-county')
  ON CONFLICT (state_id, slug) DO NOTHING;

INSERT INTO cities (county_id, name, slug, latitude, longitude, population)
  VALUES (
    (SELECT id FROM counties WHERE slug = 'webb-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas')),
    'Laredo', 'laredo', 27.5036, -99.5076, 255205
  )
  ON CONFLICT (county_id, slug) DO UPDATE SET latitude = excluded.latitude, longitude = excluded.longitude, population = excluded.population;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'laredo' AND county_id = (SELECT id FROM counties WHERE slug = 'webb-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-1', 'r-1', 'Single-Family Residential', 'Single-family residential district for detached homes on standard lots.',
    35, NULL, 7500, 50,
    25, 5, 5, '2 spaces per dwelling unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-1' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo')
    AND pu.name IN ('Single-Family Detached', 'Home Occupation', 'Place of Worship')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'laredo' AND county_id = (SELECT id FROM counties WHERE slug = 'webb-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'R-3', 'r-3', 'Multi-Family Residential', 'Multi-family district for apartments, condominiums, and townhomes.',
    45, NULL, 5000, 60,
    20, 10, 5, '1.5 spaces per unit.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'r-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo')
    AND pu.name IN ('Apartment', 'Condominium', 'Townhouse', 'Duplex')
  ON CONFLICT DO NOTHING;

INSERT INTO zones (city_id, zone_code, zone_code_slug, zone_name, description, max_height_ft, far, min_lot_size_sqft, max_impervious_cover_pct, setback_front_ft, setback_rear_ft, setback_side_ft, parking_requirement)
  VALUES (
    (SELECT id FROM cities WHERE slug = 'laredo' AND county_id = (SELECT id FROM counties WHERE slug = 'webb-county' AND state_id = (SELECT id FROM states WHERE slug = 'texas'))),
    'B-3', 'b-3', 'General Business', 'General business and commercial district for retail, office, and service uses.',
    60, NULL, 5000, 85,
    0, 0, 0, '1 space per 250 sqft.'
  )
  ON CONFLICT (city_id, zone_code_slug) DO UPDATE SET zone_name = excluded.zone_name, description = excluded.description, max_height_ft = excluded.max_height_ft, far = excluded.far, min_lot_size_sqft = excluded.min_lot_size_sqft, max_impervious_cover_pct = excluded.max_impervious_cover_pct, setback_front_ft = excluded.setback_front_ft, setback_rear_ft = excluded.setback_rear_ft, setback_side_ft = excluded.setback_side_ft, parking_requirement = excluded.parking_requirement;

INSERT INTO zone_permitted_uses (zone_id, permitted_use_id)
  SELECT z.id, pu.id FROM zones z, permitted_uses pu
  WHERE z.zone_code_slug = 'b-3' AND z.city_id = (SELECT id FROM cities WHERE slug = 'laredo')
    AND pu.name IN ('Retail Sales', 'Restaurant (General)', 'Office (General)', 'Personal Services', 'Drive-Through Facility')
  ON CONFLICT DO NOTHING;
